### ISSUE TITLE
[QST] Use stream-k feature in cutlass profiler

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/cutlass#1004]
Hi, 

Apologies in advance if my questions are noobish, I am getting familiar with cutlass.

I am learning about the use of stream-k to improve perf for particular shapes. I'd like to sweep other params like tile sizes and also stream-k to get best perf for tensorop gemms. 

My question is, how can I set a stream-k option using cutlass profiler if it is implemented there? I only saw the example (47). 

Also, is fixed-split implemented? I know about split_k_slices and mode in cutlass profiler but not sure if "fixed-split" is incorporated in these (global sync with L2 atomic reduction).

Thanks.

**Comment by MustafaFayez** [comment]
Thank you for the prompt response! 
What about the fixed-split configuration where I don't want to launch a separate kernel to reduce across K? How can I do that in cutlass profiler? I want to split across k but within one kernel using atomic reduction in L2.
I noticed when I set split_k_slices it always launches two kernels, maybe I am wrong?

**Comment by hwu36** [comment]
unless you set split k mode to parallel, it won't launch the 2nd reduction kernel.  the gemm kernel  itself can do the reduction in the epilogue and we call this serial spiltk.

**Comment by MustafaFayez** [comment]
gotcha, thanks!

**Comment by Ther-nullptr** [comment]
So do I need to change the file, and recompile the cutlass profiler?

**Comment by hwu36** [comment]
yes.  restart from the cmake step to let it generate cuda code again.

**Comment by maxwellpirtle** [comment]
> streamk is not turned on by default in the profiler. change https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/generator.py#L51 to turn it on.

The CUTLASS repo has since been updated. The old link refers to `main` instead of the commit hash at the time (probably around [this one](https://github.com/NVIDIA/cutlass/tree/146d314057c5f193a70c2b36896e739c8c60aef4)) so the link is now broken since the directories have changed.

The new permalink link as of CUTLASS 3.8 is [`python/cutlass_library/generator.py`](https://github.com/NVIDIA/cutlass/blob/389e493055f981bfdc6d4348f823191ca7b9fddd/python/cutlass_library/generator.py#L131).
