### ISSUE TITLE
See the final template function ouput

### ISSUE THREAD

**Issue by mkhairy** [NVIDIA/cutlass#101]
Hello,

Is there a compiler trick that I can do in nvcc to see the final GEMM function that is customized to my code after the template and inlining are resolved?

Thanks!

**Comment by kerrmudgeon** [comment]
One option is to insert `printf("%s\n", __PRETTY_FUNCTION__);` in the location of interest to print the fully specialized type names.

Otherwise, our recourse has been to induce compiler errors to view the resulting type (piped through `head` to avoid scrolling through thousands of lines of template spew).
