### ISSUE TITLE
[QST]How to create and use `TiledMMA` and `ThrMMA` in cute/atom/mma_atom.hpp

### ISSUE THREAD

**Issue by fecet** [NVIDIA/cutlass#1028]
Hello,

While working with the Cute library, I found the following definitions in `cute/atom/mma_atom.hpp`:

```cpp
template <class MMA_Atom,
          class AtomLayoutMNK   = Layout<Shape<_1,_1,_1>>,
          class ValLayoutMNK    = Layout<Shape<_1,_1,_1>>,
          class PermutationsMNK = Tile<Underscore,Underscore,Underscore>>
struct TiledMMA : MMA_Atom;
```

and

```cpp
template <class TiledMMA, class ThrVMNK>
struct ThrMMA : TiledMMA;
```

Upon investigating these definitions and the corresponding usage in `cutlass` within `collective_mma.hpp`, it appears that `ThrMMA` and `TiledMMA` are meant for tiling a `cute::tensor` on shared memory for a given MMA trait. In other words, these templates seem to create register fragments per thread that correspond to numbers in shared memory.

Despite thorough research in the Cute and Cutlass documentation, I was unable to find any specific information or examples on how to use `TiledMMA` and `ThrMMA`. Specifically, I'm looking for clarification on the meaning of the template parameters such as `AtomLayoutMNK`, how the `Layout` class is defined, and how to define and use these two template classes to create my fragments and call `cute::gemm` to perform MMA directly in the register for specific A, B, C sizes, such as 128x128x8 in the cute example.

If there are any detailed documents or explanations regarding this matter, please guide me. If not, it would be greatly appreciated if additional information or examples could be provided in the documentation.

Thank you so much!

**Comment by Boreaso** [comment]
Same question. Looking forward to more detailed documentation and tutorials.

**Comment by fecet** [comment]
> 

Hi there,

I noticed that you're encountering the same issue as I am. Would it be possible for you to share your email address so that we could discuss this issue related to CUTE more in-depth? I believe that by collaborating, we might be able to find a solution more quickly.

**Comment by fecet** [comment]
> **[Boreaso](/Boreaso) ** commented

Hi there,

I noticed that you're encountering the same issue as I am. Would it be possible for you to share your email address so that we could discuss this issue related to CUTE more in-depth? I believe that by collaborating, we might be able to find a solution more quickly.

**Comment by thakkarV** [comment]
An atom in CUTLASS and CuTe is defined as the smallest number of threads and data that _must_ participate together to execute an architecture intrinsic copy/math operation.

In CuTe atom layer, we warp this up with the PTX operator struct that exposes a functor struct to execute this operation, but more importantly, package up the meta-data that the PTX operation does not and cannot convey : thread and data layouts of input/output tensors.

However, this is still not general enough of a representation across architectures to define what we would call the spatial micro-kernel layer. If you survey the core inner loop MMA operations across GPU generations, you will find that each has an optimal instruction sequence that correspond to different tilings of these atoms across threads and data. `TiledMma` is a spatial-microkernel layer that allows us to construct arbitrary tilings of any mma atom across any number of threads and data. Let's look at the interface again:

```cpp
template <class MMA_Atom,
          class AtomLayoutMNK   = Layout<Shape<_1,_1,_1>>,
          class ValLayoutMNK    = Layout<Shape<_1,_1,_1>>,
          class PermutationsMNK = Tile<Underscore,Underscore,Underscore>>
struct TiledMMA : MMA_Atom;
```

Here, the `AtomLayoutMNK` is the "thread" tiling of the atom -- how many replicates of this MMA atom do you want to tile across the logical MNK projections of the tiled MMA. The `ValLayoutMNK` similarly specific the tiling across replicate values instead -- how many atoms is each thread going to issue as a part of this tiled MMA.  Generally speaking, we only use `ValLayoutMNK` in conjunction with the `PermutationsMNK` since having more than 1 atom's worth of values per thread allows us to perform permutations that make the smem layout design easier for pre-Hopper MMA instructions.

**Comment by fecet** [comment]
Hi [@thakkarV ],

First and foremost, I'd like to thank you for your patient and detailed response. It certainly helped shed light on my understanding of MMA operations and how CUTE leverages `fma` to encapsulate `ptx` for atomic MMA operations.

I am trying to wrap my head around a concrete example:

```cpp
using MMA = MMA_Atom<MMA_Traits<SM80_16x8x8_F32TF32TF32F32_TN>>;
MMA mma{};
```
In this example, I understand we're calculating a matrix of size 16x8x8, which should correspond to the MMAAtomTile size you mentioned. Let's say we have a shared memory A of size 128x128x8, a shared memory B of similar size, and a 1D block with 256 threads. In a trivial scenario, would my AtomLayout be something like make_layout(make_shape(8,16,1))? If so, how would I compute my ValLayoutMNK and PermutationsMNK?

Furthermore, for a warp (with the ThreadID size as defined in SM80_16x8x8_F32TF32TF32F32_TN), I've noticed:
```cpp
using MMA = MMA_Atom<MMA_Traits<SM80_16x8x8_F32TF32TF32F32_TN>>;
MMA mma{};
auto tiled_mma = make_tiled_mma(mma); // AtomLayout with shape (1,1,1)
auto tmma = tiled_mma.get_slice(laneIdx);
```
Here, the partition_A and partition_B methods in ThrMMA distribute 128 elements from A and 64 from B to threads in chunks of 4 and 2 respectively, ensuring the MMA Traits requirements are met. This is for non-tiled scenarios. My question is: if we introduce tiling, how do we calculate the number of registers for each thread? In a trivial (1,1,1) scenario, I've used an inner loop (looping num_mma_block_per_warp times) to achieve the entire MMA computation. What would be the partition after tiling?

Also, in the ThrMMA documentation, I see that ThrMMA accepts thread coords for easier swizzle implementation. Could you provide an example showcasing how to compose a swizzle operation to tackle bank conflict issues using this abstraction layer?

Thank you for your time and help. I look forward to your guidance.

**Comment by thakkarV** [comment]
> In a trivial scenario, would my AtomLayout be something like make_layout(make_shape(8,16,1))? If so, how would I compute my ValLayoutMNK and PermutationsMNK?

No, if you want to tile the `SM80_16x8x8_F32TF32TF32F32_TN` s.t. the tiled mma spans 256 threads, it would need to have a atom tile layout of size 256/32 = 8. A possible configuration might be `AtomLayoutMNK   = Layout<Shape<_4,_2,_1>>`

> If so, how would I compute my ValLayoutMNK and PermutationsMNK?
This totally depends on what exactly you are trying to do. In general, as I said in my original post, val tilings and permutations are very useful when you want to interleaves the values of multiple MMAs together in order make designing smem layouts easier.

> My question is: if we introduce tiling, how do we calculate the number of registers for each thread? In a trivial (1,1,1) scenario, I've used an inner loop (looping num_mma_block_per_warp times) to achieve the entire MMA computation. What would be the partition after tiling?

You don't have to do any of this, the tiled MMA partitioner will create the fragments for you you and any loop iterations can be canonical loop structures that just span the size of the partitioned fragments (which the cute algorithm `gemm` handles for you as well). You can see how we use it in https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L231

> Also, in the ThrMMA documentation, I see that ThrMMA accepts thread coords for easier swizzle implementation. Could you provide an example showcasing how to compose a swizzle operation to tackle bank conflict issues using this abstraction layer?

Are you referring to the comment "Use ThrVMNK and thrfrg rather than thr_idx and tidfrg to support swizzled threads partitioning dynamic layouts"? If so, that refers to swizzled `AtomLayoutMNK` and is not referring to swizzled smem layouts. An example of swizzle atom layouts is the tiled mma for Volta:

```cpp
    SM70_8x8x4_F32F16F16F32_NT mma;

    auto tiled_mma = make_tiled_mma(mma,
                                    composition(Swizzle<1,0,-1>{},
                                                Layout<Shape <Shape <_2,_2>,Shape <_2,_2>>,
                                                       Stride<Stride<_1,_4>,Stride<_2,_8>>>{}),
                                    Layout<Shape<_2,_2>>{},
                                    Tile<Layout<Shape<_4,_2,_2>,Stride<_1,_32,_8>>,
                                         Layout<Shape<_4,_2,_2>,Stride<_1,_32,_8>>>{});

```

**Comment by cctry** [comment]
> val tilings and permutations are very useful when you want to interleave the data of multiple MMAs together in order make designing smem layouts easier

@thakkarV Could you please provide more details about this?

**Comment by sophiawisdom** [comment]
Instead of emails I made a discord so we can discuss issues like this: https://discord.gg/EgHrZbaq.

**Comment by mnicely** [comment]
@fecet has your issue been resolved?
