### ISSUE TITLE
[QST] run cutlass_profiler with batch_count > 1 and split_k_slices > 1

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/cutlass#1061]
Hi, 

is it possible to run cutlass_profiler for batched gemms while also doing split_k reduction across threadblocks (split_k_slices>1). 

Such combo is helpful in shapes like b=16,m=64,n=64,k=8192 where the batch count is not too large to fill all SMs yet. 

If this feature is not implemented yet in cutlass_profiler nor cutlass, how can it be implemented from scratch? 

Thank you.

**Comment by hwu36** [comment]
See #1033

**Comment by hwu36** [comment]
may be just run different batches in different streams.

**Comment by MustafaFayez** [comment]
Thanks for the prompt responses. I'm a beginner in cutlass, would this https://github.com/NVIDIA/cutlass/issues/1033#issuecomment-1670566281 be applicable to cutlass_profiler?

**Comment by MustafaFayez** [comment]
it would be great if you can guide me into doing the necessary changes to implement this feature in my cutlass src. Thanks.

**Comment by hwu36** [comment]
In batch gemm, different `grid.z` (`threadblock_tile_offset.k()` is basically `grid.z`) are used to handle different batches. See https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/gemm_universal.h#L505

In splitk, different `grid.z` are used to handle different k slices.  See https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/gemm_universal.h#L503

So, in your cases, `grid.z` would be divided to handle both different batches and different k slices.  just search `params.mode` in https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/gemm_universal.h#L503 to check how different mode are taken care of.  Note, serial splitk mode is just `kGemm`.  If `threadblock_tile_offset.k()` is larger than 1, then it is serial splitk, otherwise it is a regular gemm.
