### ISSUE TITLE
[QST] Adding counters/timers to a GEMM kernel

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/cutlass#1063]
Hi, 

I am a cutlass noob, so apologies in advance. 

I am trying to understand where a GEMM kernel execution time is spent, I am interested in a specific shape (8192,1024,128) (m,n,k) on a volta device using Tensor Cores. 

I tried looking at profiling tools like nsight compute, however, I think more details are needed.

So, I am trying to add timers (maybe using cuda event record?), for example in between wmma instructions? 
My question is how to do this in cutlass? as in where should I add those timers or is it possible to have a single cu file that implements such kernel where its contents are copied from different cutlass file? Feel free to point out any documentation if you think it would help me understand the code structure. 

Thanks.

**Comment by hwu36** [comment]
check https://forums.developer.nvidia.com/t/reading-globaltimer-register-or-calling-clock-clock64-in-loop-prevent-concurrent-kernel-execution/48604 for the timer.

adding timer before and after a single instruction would not work since modern cpu/gpu pipelines the instruction execution.

your k is small.  so mainloop is short, the kernel will spend relatively more time on the prologue and epilogue.  also, you use `wmma` which is slower than `mma.sync`

**Comment by MustafaFayez** [comment]
Thanks for your reply! I do agree that the epilogue might be the perf bottleneck in such shape, so how can I use the global timers in such case in cutlass?

**Comment by hwu36** [comment]
this gemm size should be memory bound.  nsight should be able to tell you that.
