### ISSUE TITLE
Why use CUTLASS instead of CUBLAS for GEMM? What are the advantages of CUTLASS ?

### ISSUE THREAD

**Issue by ZhaoJob** [NVIDIA/cutlass#109]

**Comment by timespacce** [comment]
Hallo,

cuBLAS is well-documented and from by observations faster than cuTLASS. For production use-cases I personally use cuBLAS.

But cuBLAS is not open source and not complete. In many cases people would like to expand it, but it's not possible because neither a theoretical explanation nor a source code of the used algorithms is available. It's a secret how cuBLAS internally works and if it's written in pure CUDA or PTXAS or something else. 

For scientific purposes and experiments one can use cuTLASS as a beginning point. GEMM is in the core of nVIDIA because thats what the Tensor Cores do the best. Deep learning frameworks such as cuDNN are a mixture of modification and expansion of cuBLAS. If someone want's to improve them its very important to have a basic such as cuTLASS. I find it very helpful that the cuTLASS community shares with us both algorithmic explanations and conrete code implementations. 

Best Wishes,
James.

**Comment by ZhaoJob** [comment]
Thanks, you fully explained my doubts.

**Comment by cliffburdick** [comment]
> Thanks, you fully explained my doubts.

For what it's worth, cuBLASLt uses CUTLASS kernels under the hood. You can verify this by looking at the profiler.

**Comment by hwu36** [comment]
CUDA 11.3 significantly improves the performance of Ampere/Turing/Volta Tensor Core kernels.  See #241 .  

You many want to do the benchmarking again with the latest compiler.

A general answer to cutlass vs. libraries (e.g. cudnn/cublas)

- If you just need an api, cudnn is worry-free one-stop shop. 
- You would need cutlass, when
1. You need source code to customize cutlass,  or to just use some cutlass sub-modules, or to piecemeal cutlass for a DL/HPC compiler, etc.
2. cuDNN may not pick the best kernels for your problem sizes, existing cutlass kernels or customized cutlass kernels can outperform the library in these cases.
3. libraries like cudnn/cublas are huge and > 99.9% of their kernels are not needed by a typical user.  in cutlass, you just need to instantiate what you need.
4. libraries like cudnn/cublas has CPU overhead.  This overhead can be minimum in cutlass if you know what kernel you want.  It is important for small problem size.
