### ISSUE TITLE
Fragment access index is not correct in tensor op's RegularTileIterator?

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/cutlass#122]
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_iterator_tensor_op.h#L575
I think this line should be
```
int access_idx = c * ThreadMap::Iterations::kStrided + s;
```
This tile iterator will be used with a `TransposedThreadMap`.
When calling the iterator's method `store(Fragment const& frag)`, the input fragment is loaded by a global memory tile iterator. But the global tile iterator is used with a `NonTransposedThreadMap`, this causes the order of elments of the fragment is different in the two tile iterator.

**Comment by hwu36** [comment]
Very glad to see people digging into the iterators.  The code is correct.

This iterator is used in the case i) if it is A operand, it is row major ii) if it is B operand, it is column major.  You can follow https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/test/unit/gemm/threadblock/mma_pipelined_sm75.cu#L235 to see how the global iterator works with this iterator.

If A operand is column major or B operand is row major, we use this iterator https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/threadblock/regular_tile_iterator_tensor_op.h#L51.

https://github.com/NVIDIA/cutlass/tree/master/examples/03_visualize_layout is utility tool to visualize the data layout, it can help you understand how data are stored in the global memory and shared memory.

Note: interleaved layout of integer tensor op is different.  If this is what you are working on, let me know.

**Comment by xiaocenxiaocen** [comment]
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/default_mma_core_sm75.h#L1221
I am working on the interleaved layout of integer tensor op. In the specialization for A operand with layout `ColumnMajorInterleaved<32>` and B operand with layout `RowMajorInterleaved<32>`, the thread map of global tile reading iterator is a `PitchLinearWarpRakedThreadMap` and the thread map of shared memory tile writing iterator uses the transpose version of thread map of the global tile iterator.     
The `PitchLinearWarpRakedThreadMap` first partition warps in the stride dimension, then the contiguous dimension. This causes the `Iterations::kStrided` to be equal to 1, and then the `Iterations::kContiguous` of transposed thread map is equal to 1 either. In this case, the fragment index of `RegularTileIteratorTensorOp` is correct.  
But if the thread map first partition warps in the contiguous dimension, the `Iterations::kStrided` will be greater than 1. In this case, the fragment index will be incorrect. Because the reading/writing order of the fragment is different for the global tile reading iterator and the shared memory tile writing iterator.  
The reason for changing the partition order of the thread map is that partitioning contiguous dimension firstly will reduce the allocated register count in some cases.

**Comment by hwu36** [comment]
So happy to see you go this far!

You are 100% correct about how we implemented interleaved layout for integer tensor op.  We mapped ColumnMajorInterleved<32>(m, n) to ColumnMajor(m x 32, n / 32) so that we can reuse the ColumnMajor global iterator.  It's shared store iterator is the same as the crosswise shared store iterator which is used by fp16 tensor core kernels.  So, the only thing we need to do is to swap the coordinates as you already noticed because the coordinates used by the global and shared store iterators are transposed.

I can understand that if you change the behaviour of the threadmap, the existing code won't work because everything has to be clicked.  However, we cannot change our existing code because it is reused by fp16 tensor core kernels.  So I suggest you can modify your local version to meet your need.

Again, you did great job in hunting down our implementation.  We are more than happy to know more about your future progress.
