### ISSUE TITLE
[QST] How to choose a proper ValLayout?

### ISSUE THREAD

**Issue by mammoth831** [NVIDIA/cutlass#1242]
Hi, @ccecka

https://github.com/NVIDIA/cutlass/blob/a75b4ac483166189a45290783cb0a18af5ff0ea5/test/unit/gemm/device/default_gemm_configuration.hpp#L166-L172

For a kernel with TileShape `128x128x32`,  the TiledMMA uses `2x2x1` AtomLayout and `1x2x1` ValLayout, with corresponding `32x32x16` TiledShape_MNK in TiledMMA. Then I think cute will use the TiledMMA to tile `128x128x32`.

Can we just set the ValLayout to `4x8x1` to make TiledShape_MNK `128x128x16`?  Then for `M-` and `N-` extent, we can process them "once".

And could you please give some suggestions on how to choose a proper ValLayout?

**Comment by ccecka** [comment]
You can absolutely set `ValLayout` to `4x8x1` to get a `128x128x16` MMA. With `print_latex(tiled_mma)`, this can be very helpful for visualization.

However, the MMA partitioner will still partition any `MxN` tensor into a `(MMA, MMA_M, MMA_N)` tensor where the `MMA`-mode is for a single instruction and `MMA_M` and `MMA_N` modes are the number of instructions in `M` and `N` respectively. Thus, `ValLayout` won't actually affect the partitioning. It is actually being removed as a parameter in the next revision because it only interacts with the `Permutation` parameter in an unintuitive way and is difficult to explain. Feel free to ignore it.
