### ISSUE TITLE
[QST] What is the difference between make_shape and make_tile?

### ISSUE THREAD

**Issue by ZhangZhiPku** [NVIDIA/cutlass#1297]
Thank you for your great work, for both cutlass and cute.

I'm following instructions to build my program. I use make_tensor to build rav as a pointer to specific register memory, and use local_tile to select a segment of its data. To make a this selection, I use make_shape function to define a space with a shape of [1, VPT], however i notice that make_tile(1, VPT) serves the same purpose. Could you explain the difference between using make_tile and make_shape here?

```python
    auto rav = cute::make_tensor(make_rmem_ptr(local_acc), make_shape(VEC_LEN, VPT), make_stride(VPT, 1));
    auto ravT = cute::local_tile(rav, make_shape(1, VPT), make_coord(i, 0));
```
And there is another problem of shape declaration: I found i can always use constant statement like (1, VPT) to make shape declaration instead of (Int{1}, Int{VPT}), does this definition going to slow down the execution later?

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
A tile is a tuple of layouts. If you divide with a shape, that is equivalent to divding with a tile of trivial layouts (layouts who have the same shape, and left major compact strides). So in your case, `make_tile()` is overkill since you do not need arbitrary strides for your tiling. 

As for `make_shape(1, VPT)` being slower than `make_shape(Int<1>{}, Int<VPT>{})`, yes, if you use dyamic integer types there, it can lead to inefficinet code generation than using integral constants.
