### ISSUE TITLE
[QST] `retile_D` in mainloop

### ISSUE THREAD

**Issue by jeromeku** [NVIDIA/cutlass#1356]
**What is your question?**

In `Cutlass 3.0` `gemm` mainloop, why is it necessary to retile `operand A` and `operand B` registers when using an SmemCopyAtom (e.g., `ldmatrix`)?

For example, in `gemm::collective::sm80_mma_multistage.hpp`, `tCrA` and `tCrB` are first obtained by obtaining respective thread slices from `TiledMMA` [here](https://github.com/NVIDIA/cutlass/blob/bbe579a9e3beb6ea6626d9227ec32d0dae119a49/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L232-L235), then later retiled using the `SmemCopyAtom` along with the previously defined `tiledmma` [here](https://github.com/NVIDIA/cutlass/blob/bbe579a9e3beb6ea6626d9227ec32d0dae119a49/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L251-L252).

Then, when iterating over the `k tiles`, [pre-fetching / copying](https://github.com/NVIDIA/cutlass/blob/bbe579a9e3beb6ea6626d9227ec32d0dae119a49/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L310-L311) from `smem` to registers is done on the retiled `views` while [`gemm`](https://github.com/NVIDIA/cutlass/blob/bbe579a9e3beb6ea6626d9227ec32d0dae119a49/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L330) is executed on `tCrA` and `tCrB`.

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
The retiling is composing some partitioned tensor's layout (some V layout, since the T part has been sliced away already) with the partitioner V layout of the copy atom ldmatrix. This retiling is needed because the V partitioners of the copy operation may not the same as the mma atom. If you peek inside the implementation of retile, its just a simple composition with the V layout
