### ISSUE TITLE
Incorrect disposition of f16 gemm when using cuda 11.1

### ISSUE THREAD

**Issue by huyz-git** [NVIDIA/cutlass#145]
When compiling `cutlass` with `cuda 11.1`, and then run `cutlass_profiler` with `--accumulator-type=f16`, it shows `Disposition: Incorrect`:
![cuda111](https://user-images.githubusercontent.com/22879638/97970788-08699280-1dfd-11eb-9b7b-4ada793d6353.png)

When compiling `cutlass` with `cuda 10.2`, and then run the same thing, then disposition is correct:
![cuda102](https://user-images.githubusercontent.com/22879638/97970815-11f2fa80-1dfd-11eb-9147-c3ef78393b6b.png)

Additional information:
- Card: Tesla V100 SXM2
- Driver: 455.32.00 from NVIDIA's cuda repo
- OS: Centos 8, with cmake 3.18 installed by anaconda
- Compile method: `export PATH=/usr/local/cuda-(version)/bin:$PATH`; `cmake .. -DCUTLASS_NVCC_ARCHS=70`; `make -j60`

**Comment by manishucsd** [comment]
Thanks for bringing this up. A few pointers for you to resolve this at your end:

- Since this is a large-K F16 accumulation, I recommend trying input distributions with reduced range and see if the behavior changes.
For example:
```
./tools/profiler/cutlass_profiler --m=8192 --n=8192 --providers=cutlass --k=1024,2048,4096,8192 --profiling-enabled=false --dist=uniform,min:-3,max:3 
```

- CUTLASS profiler supports verification check against cuBLAS, device, and host reference. (`--verification-providers=device,host,cublas`). The device and cublas should be picked as default verification providers. I recommend trying them all for your case. 

- Examine the miss-matches, if any, using `--save-workspace=incorrect`

Closing the issue. Please feel free to re-open, if you need more assistance on it.
