### ISSUE TITLE
[QST] `ThreadblockSwizzleStreamK` cost modeling questions

### ISSUE THREAD

**Issue by HanGuo97** [NVIDIA/cutlass#1489]
**What is your question?**

In the [`get_sk_blocks`](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle_streamk.h#L98) of `ThreadblockSwizzleStreamK`, the cost modeling has the following lines:

```cpp
      if (trial_sk_blocks % sk_tiles == 0)
      {
        // aligned
        num_peers = (trial_sk_blocks / sk_tiles);

        iter_cost = 0.0f;
      }
```

However, I'm wondering if the condition supposed to be `sk_tiles % trial_sk_blocks == 0` instead? For example, imagine there are 20 SK Tiles to be scheduled into 4 blocks. In this case, there is no need for fixup as each threadblock can handle 5 tiles (aligned).

**Comment by hwu36** [comment]
@jackkosaian

**Comment by jackkosaian** [comment]
`iter_cost` in the cost model is attempting to account for performance overhead coming from skewed accesses of K tiles when computing partial MMA results.

As described in Section 5.2 of the [stream-K paper](https://arxiv.org/abs/2301.03598), stream-K can introduce some skew in accessesing tiles of A and B. For example, when one block starts at K tile 34 of output tile (0, 0) and another starts at K tile 6 of output tile (1, 0), the two blocks may have little opportunity to get L2 reuse out of loads of blocks of column-tile 0 of matrix B.

Thus, `iter_cost` will be greater than 0 when this tile-processing skew is expected to occur.

The code snippet you've pasted is accounting for the case in which the "trial" stream-K decomposition is equivalent to a split-K decomposition -- the number of tiles to compute in a stream-K fashion evenly divides the number of blocks, so we can evenly split each output tile by a factor of `trial_sk_blocks / sk_tiles`. In this case, there will be no tile processing skew, since blocks will compute starting at specific K tile offsets (e.g., for a problem with 64 K tiles and a splitting factor of 4, the possible K offsets would be 0, 16, 32, and 48). Therefore, in this case, `iter_cost` is modelled as 0.

**Comment by HanGuo97** [comment]
Ah, got it, thanks for the very clear explanation! (I didn't realize this is used to account for the lack of L2 reuse.)
