### ISSUE TITLE
Question about moving shared memory iterator

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#152]
https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_pitch_linear.h#L188

I don't understand why regular tile access iterator should move along the contiguous dimension. Per my understanding it should only move along strided dimension (for operand A, in row dimension, for operand B in column dimension). 
Even it does need to move along contiguous dimension, shouldn't it be "coord.contiguous() * ThreadMap::kElementsPerAccess +” ?

**Comment by hwu36** [comment]
Several things.

1. `add_tile_offset()` adds offset in the unit of threadblock tile, or we called kblock in some comments.  For example, when we call `add_tile_offset({1,1})`, it means we add 1 threadblock tile in the contiguous dimension and 1 threadblock tile in the strided dimension.  So, the offset of this method is a function of `Shape`, but has nothing to do with the `ThreadMap` which decides the offset of a thread inside a threadblock.
2. In GEMM/Conv implementation, `add_tile_offset()` is used to move in the k dimension.  For row major A operand, k dimension is contiguous dimension; For col major A operand, k dimension is strided dimension; For row major B operand, k dimension is strided dimension; For col major B operand, k dimension is contiguous dimension.  We have an extra layer iterator class (https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_pitch_linear.h#L207 and https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_pitch_linear.h#L304) to map the dimensions of different layouts down to the pitch linear dimension in the base class.
3. We don't want to limit the usage of our modules to one application (e.g. GEMM or CONV), so we need to implement a general solution so that the modules can be used in different scenarios.

**Comment by Peter9606** [comment]
> Several things.
> 
> 1. `add_tile_offset()` adds offset in the unit of threadblock tile, or we called kblock in some comments.  For example, when we call `add_tile_offset({1,1})`, it means we add 1 threadblock tile in the contiguous dimension and 1 threadblock tile in the strided dimension.  So, the offset of this method is a function of `Shape`, but has nothing to do with the `ThreadMap` which decides the offset of a thread inside a threadblock.

Thanks for the explanation about "kblock".
But I'm afraid `add_tile_offset()` does have something to do with `ThreadMap`, for in the full formula `coord.contiguous() * Shape::kContiguous + coord.strided() * Shape::kStrided * stride_ * ThreadMap::kElementsPerAccess`, there is a `ThreadMap` here.
Per my understanding, RegularTileIterator is only used to move over shared memory, and only moves between stages.Because most of the cases, there are only 2 stages (shared memory is split into two blocks of same size), RegularTileIterator can only switch between them. Is there anything wrong with my understanding?

> 2. In GEMM/Conv implementation, `add_tile_offset()` is used to move in the k dimension.  For row major A operand, k dimension is contiguous dimension; For col major A operand, k dimension is strided dimension; For row major B operand, k dimension is strided dimension; For col major B operand, k dimension is contiguous dimension.  We have an extra layer iterator class (https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_pitch_linear.h#L207
>     and https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_pitch_linear.h#L304
>    ) to map the dimensions of different layouts down to the pitch linear dimension in the base class.
> 3. We don't want to limit the usage of our modules to one application (e.g. GEMM or CONV), so we need to implement a general solution so that the modules can be used in different scenarios.

**Comment by Peter9606** [comment]
Thanks for your explanation. 
Same question about RegularTileIterator here:
https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear.h#L234
RegularTileIterator is used to point to threadblock tile of different stages in shared memory. My understanding is that threadblock tiles of different stages are arranged linearly in shared memory. 
So move between them, should only jump in units of `RegularTileIterator::Shape::kCount` if not considering padding. 
For in shared memory at least for SIMT, operand A is always column-like major and operand B is always row-like major, and considering the padding, the formula should be `int offset = sizeof_bits<Element>::value * (coord.strided() * Shape::kStrided * stride_) / 8;`
Is anything wrong with my understanding?

**Comment by hwu36** [comment]
The current sm50 SIMT implementation hard coded shared memory layout in a way that A is always column major and B is always row major.  In that case, the k dimension is always the strided dimension and it only needs to move in the strided dimension.

However, it is not the only way (or even the best way) to implement this.  I think it is totally okay if we set the shared memory layout to be the same as the global memory layout for the sm50 SIMT kernels so that we only need to consider the logical coordinates without thinking about the physical layout in the memory and we may also save some registers in the address computations.

Moreover, this iterator is not only used by sm50 SIMT kernels.  For example, it is also used to store sparse meta data into the shared memory for SM80 sparse tensor core GEMM.  We try to keep every iterator as general as possible so that we can reuse them whenever it is possible.  To achieve this, we need to think about all the cases even they are not needed at the moment.  This is one of the souls of CUTLASS - being a framework of kernels instead of a collection of kernels.

**Comment by Peter9606** [comment]
Clear enough! Thank you very much!
