### ISSUE TITLE
Scalar load in tile iterator simt?

### ISSUE THREAD

**Issue by illava** [NVIDIA/cutlass#163]
Is it a speedup of CUTLASS_SIMT_EPILOGUE_USE_SCALAR_STORES?
and if so, why not scalar load here? It seems symmetric.

https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/epilogue/warp/tile_iterator_simt.h#L223-L229

**Comment by hwu36** [comment]
Usually, vectorized load/store are better because they can save instructions and use memory bandwidth more efficiently.  However, vectorized load/store has higher requirement for register allocation in the compiler.  You can try to use vectorized store in your case to see if it works for you better.
