### ISSUE TITLE
ImageToColumn Implementation

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#168]
Hi, All 

I just wondering if there is any highly efficient implementation of `imageToColumn`/`columnToImage` operation, like convolution operations in CUTLASS, such that implicit GEMM can be used for convolution computation in DNNs.

Thanks!

**Comment by hwu36** [comment]
I may misinterpret your questions and my answers below may not be relevant. 

1. CUTLASS does not have imageToColumn/columnToImage code because CUTLASS convolution does not need it.
2. CUTLASS convolution is an implicit gemm implementation which does not generate matrices explicitly.  CUTLASS maps convolution to a GEMM problem internally.  See https://github.com/NVIDIA/cutlass/blob/master/media/docs/implicit_gemm_convolution.md
3. The input layout to CUTLASS convolution is NHWC in most cases which is the same as cuDNN.
4. You can type in Chinese.  I can read and write in Chinese.

**Comment by YukeWang96** [comment]
Ok, got it, thanks!

I have another question regarding the data loading.

> is there an option in CUDA that we can directly load data from global to shared memory without passing the thread-local registers?

Thanks!

**Comment by hwu36** [comment]
You can use this https://developer.nvidia.com/blog/controlling-data-movement-to-boost-performance-on-ampere-architecture/

Or you can use its ptx equivalents https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-cp-async.

cutlass uses ptx version: https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/memory_sm80.h
