### ISSUE TITLE
[QST] Does the grouped GEMM support stream-k on hopper?

### ISSUE THREAD

**Issue by jimurk** [NVIDIA/cutlass#1941]
**What is your question?**
I modified 57_hopper_grouped_gemm.cu with StreamKScheduler as following:

> using GemmKernel = cutlass::gemm::kernel::GemmUniversal<
    ProblemShape,
    CollectiveMainloop,
    CollectiveEpilogue,
    cutlass::gemm::StreamKScheduler
>;

and compiled this example, but got an error:
`cutlass/include/cutlass/gemm/kernel/sm90_gemm_array_tma_warpspecialized_cooperative.hpp(106): error: static assertion failed with "Ptr-Array Cooperative and Grouped Gemm Cooperative kernel only supports the default scheduler."  static_assert(cute::is_void_v<TileScheduler_>,
          detected during instantiation of class "cutlass::gemm::kernel::GemmUniversal<ProblemShape_, CollectiveMainloop_, CollectiveEpilogue_, TileScheduler_, std::enable_if_t<std::is_base_of_v, void>> [with ProblemShape_=ProblemShape, CollectiveMainloop_=CollectiveMainloop, CollectiveEpilogue_=CollectiveEpilogue, TileScheduler_=cutlass::gemm::StreamKScheduler]"`

It seems that grouped GEMM doesn't support stream-k, can the implementation of the grouped GEMM in cutlass support stream-k on hopper with a little modification? I have some GEMM case with small m and large n&k, i want to optimize these cases with stream-k.

**Comment by jackkosaian** [comment]
You're correct that grouped GEMM and stream-K cannot currently be used at the same time in CUTLASS.

It is possible to implement stream-K with grouped GEMM, but doing so requires passing in problem sizes to be computed in the grouped GEMM to an on-host method that sets up the stream-K decomposition. For many current uses of grouped GEMM, host-side problem sizes are not realistic.

> I have some GEMM case with small m and large n&k, i want to optimize these cases with stream-k.

Regardless of what I said above, I think you should think carefully about the expected benefit you would get from stream-K. Stream-K helps to balance work more evenly among SMs. Grouped GEMM itself attempts to saturate the GPU by running multiple problems within a single kernel. You may find that the theoretical improvement from stream-K in your grouped GEMM use case may be low due to the grouped GEMM already saturating the GPU.

**Comment by jimurk** [comment]
Thanks! I got it.
