### ISSUE TITLE
Convolution/cross-correlation example

### ISSUE THREAD

**Issue by mratsim** [NVIDIA/cutlass#20]
I think it would be extremely useful to have a 2D convolution or cross-correlation example.

Those have a lot of applications, in particular:

  - Deep Learning
  - Image and video processing (blur, edge enhancement, embossing, sharpening, denoising ...)

**Comment by tjingrant** [comment]
I've been trying to figure this out as well. Looking through the code base, especially tile_iterator.h, the access pattern of the input matrix allows little flexibility to visit input matrix in a moving-window way (and take care of paddings etc), this is necessary for implementing efficient convolution by implicit gemm method.

I'm guessing that there needs to be something like a `moving_window_traits` and `moving_window_iterator` to be implemented before one can implement convolution efficiently, which may not be that difficult. However, I'm not sure if this is ultimately useful for Deep Learning, since you already have CuDNN or TensorRT right around the corner.

**Comment by mratsim** [comment]
Convolution is at the heart of image processing and sharpening/denoising/blurring are very useful as a preprocessing step as well.

Beyond classic convolution, I see 3 benefits to such a tutorial:

### 1. Unshared convolutions / Locally Connected Layers

CuDNN doesn't support "Unshared convolution" also called "Locally Connected Layers" which instead of reusing the same convolution filter stacks new one after moving by the unshared convolution stride. This currently lacks efficient implementation but this is the key operation for [Facebook's DeepFace (CVPR 14')](http://www.cs.toronto.edu/~ranzato/publications/taigman_cvpr14.pdf).

Being able to use Cutlass to implement it would be great and it should be simple to go from convolution to unshared convolution.

I've linked implementations in this issue: https://github.com/mratsim/Arraymancer/issues/255.

### Research in modified convolutions

Beyond unshared convolutions it would be useful to experiment with new convolution-inspired schemes. This can be as simple as using a custom activation function during the convolution pass or something more complex like upsampling or super-sampling

### Implement efficient pooling layer

Pooling layers like Max-Pooling, ROI Pooling (Region of Interest Pooling) and InstanceNorm2D can be implemented using the same tiled stepping as convolutions. ROI Pooling is key for object detection and self driving car but not supported natively in CuDNN. InstanceNorm2D is key for neural style transfer (see paper [Instance Normalization: The Missing Ingredient for Fast Stylization](https://arxiv.org/abs/1607.08022)).

Being able to accelerate these workflows without having to wait for the CuDNN team would be great.

### Einsum and other Tensor contractions

Having a non-trivial example of using Cutlass might expand it to using it for `einsum` (Einstein summation).

Several thing in Deep Learning can be expressed as einsum: [convolution](http://jessicastringham.net/2018/01/01/einsum.html), [batch_matmul, bilinear, treeqn and attention networks](https://rockt.github.io/2018/04/30/einsum).

There is a lot of research into efficient Einsum expression for computational image processing in [Halide-lang](http://halide-lang.org/) and [Facebook's Tensor Comprehensions](https://github.com/facebookresearch/TensorComprehensions)

### AR / VR / 3D videos

Also in the future, we will probably need 4D convolution (Time, Depth, Height, Width) for augmented reality and virtual reality.

**Comment by tjingrant** [comment]
Thanks for your thoughtful summary. I'm a bit uncertain about point 3, 4, 5 because:
1. Pooling is significantly less computationally intense and does not occur frequently; and it's tangential to CUTLASS (although i see the connection you're trying to draw with a moving window iterator).
2. You get efficient einsum optimization in DSL's like Halide and TC with much more automated, model-driven and heavi-handed optimization with much greater flexibility; since a compiler ultimately is more flexible than a template library. This direction is likely not cost-effective, in my opinion to be done in CUTLASS.
3. I'm a bit dubious about the efficacy of 4D convolution and its computational feasibility. However, I believe you don't have to look beyond 3D convolution to find CuDNN's shortcomings. From what I can read up in the documentation, CuDNN does not have efficient winograd-based convolution for 3D case, which can be very useful, if implemented using CUTLASS. c.f. intel's recent work https://dl.acm.org/citation.cfm?id=3178496 .
 
I believe there are great values in making CUTLASS the solution to your problem 1 and 2. I'd love to extend cutlass for the above purpose. I agree that CuDNN is constantly behind the research demand. I wonder what the cutlass's maintainer @kerrmudgeon has to say about this proposal.

I'm willing to try to contribute and I wonder if there could be any coordination with NVidia's internal plan so as to not make this effort in vain, since it likely entails large amount of time and effort.

**Comment by mratsim** [comment]
For your point 2: I meant, Halide and TC could use Cutlass for their basic CUDA routines.

Might be worth it to get @jdemouth input as well (from CuDNN team).

**Comment by timespacce** [comment]
Hallo,

I would like to upvote this topic. Such an example is very important not only for better GEMM understanding but also for utilizing the full hardware potential.

The most efficient way of performing convolution and activation simultaneously is currently via **cudnnConvolutionBiasActivationForward**. Its fastest combinations are based on **CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_​PRECOMP_GEMM** and currently support only two activation functions. Due to the fact that cuDNN is closed source and the lack of intentions to include more activations, it would be very nice if we had the option to take an efficient GEMM-based convolution implementation and expand it via an activation function.

Greetings!

**Comment by YashasSamaga** [comment]
I had considerable trouble finding examples of using CUTLASS for deep learning.

I have implemented explicit GEMM and Winograd non-fused convolution using CUTLASS [here](https://github.com/YashasSamaga/ConvolutionBuildingBlocks). It's not very clean but probably serves as good examples. It also supports fusing convolution with activation or anything that you like. The Winograd implementation is also faster than cuDNN in many cases.

**Comment by mratsim** [comment]
Excellent result on Winograd, congrats.

I really hope we get a direct convolution example in the CUTLASS repo. `im2col` is quite memory intensive due to repacking and duplicating the memory.

**Comment by YangWang92** [comment]
@YashasSamaga  Thanks for sharing, and it works well on explicit im2col+gemm.  



I am trying to find implicit implementations on CPU/GPU, such as https://github.com/ROCmSoftwarePlatform/iGEMMgen.
Does anyone opensource implicit gemm implementations on CUDA?

**Comment by YangWang92** [comment]
Hi all, I found that megvii has opensourced their cutlass based conv, and it works well on int8. 
Thanks for their hard work!

https://github.com/MegEngine/cutlass

**Comment by hwu36** [comment]
As fully discussed in [implicit_gemm_convolution.md](https://github.com/NVIDIA/cutlass/blob/master/media/docs/implicit_gemm_convolution.md), CUTLASS convolution code maximizes the reuse of the GEMM modules.  The only new part is the loading from the global memory.  

To make things even easier, we provide a two-step approach to implement the loading.  The first step is analytical.  Take NHWC layout as an example, we compute the logical coordinates (n, h, w, c) for every load and throw them into the layout object to compute the physical addresses like [this](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_analytic.h#L218).  The second step is optimized.  The offset between two loads are runtime constants which can be precomputed.  For [example](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/threadblock/conv2d_params.h#L195), `filter_c_delta = layout(n, h, w, (filter_c_ + Shape::kColumn * problem_size_.split_k_slices)) - layout(n, h, w, filter_c_)  = Shape::kColumn * problem_size_.split_k_slices`. Simple as that.

Here is the real story how fast we implemented NCxHWx Fprop.  The analytical one **worked out of the box** after we [switched to use NCxHWx layout ](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/kernel/default_conv2d_fprop.h#L235) since the global iterator implementation is layout independent.  The optimized one is a **1 hour job** since we only need to correctly set 8 pre-computed [activation](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/threadblock/conv2d_params.h#L241-L257) and [filter](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/threadblock/conv2d_params.h#L362-L376) offsets.  Epilogue and test framework surely require some extra time, but they are just mechanical work.

We know we still have some holes in our conv functionality.  For example, we don't have idp4a conv.  We welcome the community to fill the holes.

**Comment by d-k-b** [comment]
Convolution is now supported with examples!
