### ISSUE TITLE
15_ampere_sparse_tensorop_gemm fails

### ISSUE THREAD

**Issue by decioren** [NVIDIA/cutlass#225]
running 15_ampere_sparse_tensorop_gemm fails in the correctness test in the end. It seems that all values are zeros.
changing to half data type according to https://github.com/NVIDIA/cutlass/issues/103 also fails with zeros.
I tried a few fixes to the random data generation and got the host reference implementation to work, but device code still gives zeros.

a windows 10 machine with cuda 11.2. Any ideas?

**Comment by hwu36** [comment]
ACK.

Would you please show me your fix first?

**Comment by hwu36** [comment]
Never mind.  This example has several problems.  I will let you know when I fix it and I will show you the diff.

For now, you can take a look at our sparse gemm unit tests in https://github.com/NVIDIA/cutlass/tree/master/test/unit/gemm/device .  Just search "sparse" there.

**Comment by hwu36** [comment]
You can use `make cutlass_test_unit_gemm_device_sparse_tensorop_sm80` to just build all sparse device unit tests

**Comment by decioren** [comment]
Thanks for that.
I did two things: 
I changed the data initialization (TensorFillRandomUniform) to use bits=-1 rather than '0' as I was getting just zeros in the data.
I changed the data type to half so that debugging it will be easier (4bit types are hard to look at with the debugger)

**Comment by hwu36** [comment]
The fix you need is this:

diff --git a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
index c88a889..d5a2ddb 100644
--- a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
+++ b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
@@ -111,7 +111,8 @@ using Gemm = cutlass::gemm::device::SparseGemm<ElementInputA,
 
 // Data type and layout of meta data matrix E can be inferred from template Gemm.
 using ElementInputE = typename Gemm::ElementE;
-using LayoutInputE = typename Gemm::LayoutE;
+using LayoutInputE = cutlass::layout::RowMajor;
+using ReorderedLayoutInputE = typename Gemm::LayoutE;
 
 // Blow property is defined in include/cutlass/arch/sp_mma_sm80.h
 // 50% Sparsity on Ampere
@@ -151,27 +152,27 @@ int run() {
   cutlass::HostTensor<ElementInputE, LayoutInputE> tensor_e(
       cutlass::make_Coord(problem_size.m(), problem_size.k() / kSparse / kElementsPerElementE));
   // Same size as the above.  The above one needs to be reordered and stored in this one.
-  cutlass::HostTensor<ElementInputE, LayoutInputE> tensor_e_reordered(
+  cutlass::HostTensor<ElementInputE, ReorderedLayoutInputE> tensor_e_reordered(
       cutlass::make_Coord(problem_size.m(), problem_size.k() / kSparse / kElementsPerElementE));
 
   // Fill input and output matrices on host using CUTLASS helper functions
   cutlass::reference::host::TensorFillRandomUniform(
       tensor_a.host_view(),
       1,
-      ElementInputA(1),
-      ElementInputA(-1),
+      ElementInputA(2),
+      ElementInputA(-2),
       0);  // <- Fill matrix A on host with uniform-distribution random data
   cutlass::reference::host::TensorFillRandomUniform(
       tensor_b.host_view(),
       1,
-      ElementInputB(1),
-      ElementInputB(-1),
+      ElementInputB(2),
+      ElementInputB(-2),
       0);  // <- Fill matrix B on host with uniform-distribution random data
   cutlass::reference::host::TensorFillRandomUniform(
       tensor_c.host_view(),
       1,
-      ElementOutput(1),
-      ElementOutput(-1),
+      ElementOutput(2),
+      ElementOutput(-2),
       0);  // <- Fill matrix C on host with uniform-distribution random data
   cutlass::reference::host::TensorFillRandomSparseMeta(                                           
       tensor_e.host_view(),
@@ -210,7 +211,7 @@ int run() {
                                      tensor_b.device_ref(),  // <- reference to matrix B on device
                                      tensor_c.device_ref(),  // <- reference to matrix C on device
                                      tensor_d.device_ref(),  // <- reference to matrix D on device
-                                     tensor_e.device_ref(),  // <- reference to matrix E on device
+                                     tensor_e_reordered.device_ref(),  // <- reference to matrix E on device
                                      {alpha, beta},          // <- tuple of alpha and beta
                                      split_k_slices};        // <- k-dimension split factor

There are two bugs:

1. input A and B were initialized to zeros by mistake. Now they are initialized to a random integer between [-1, 0, 1].

2. The original meta data matrix we wanted to show in the example was supposed to be a row major matrix.  The sparse gemm kernel needs to take is an interleaved layout so that we can use the efficient `ldmatrix` instruction to load the data from the shared memory.  We need to call `cutlass::reorder_meta` to transform the meta data matrix from row major to this interleaved layout.  The mistake we made in this example was that we used the same interleved layout before and after the transformation.

Sorry about that.  The device kernel is solid since it is tested by the unit tests.

**Comment by d-k-b** [comment]
This issue should be resolved now, please give it a try!
