### ISSUE TITLE
How to elegently change the layout of a tensor?

### ISSUE THREAD

**Issue by zheng95z** [NVIDIA/cutlass#261]
Like if we have a tensor:
```
cutlass::HostTensor<cutlass::half_t, cutlass::layout::RowMajor> temp_light_r({ 1, 128 });
```
How to change its layout to `cutlass::layout::NWHC`, to make it immediately become:
```
cutlass::HostTensor<cutlass::half_t, cutlass::layout::NWHC> temp_light_r({ 1, 8, 8, 2 });
```

Currently, I just use `copy_host_to_host` to copy the `host_data` from the first tensor to the second tensor.

**Comment by zheng95z** [comment]
> temp_light_r(temp_light_r.host_data(), layout);

It seems this is not working for me. Just some compiling errors.

Also, I noticed that the way how `NCHW` and `NHWC` organize data is different.

For example, if we have these 8 int elements in linear memory:

```c++
int example[8] = { 1, 2, 3, 4, 5, 6, 7, 8 };
```

we then use this to fill the `NCHW`:


```c++
cutlass::HostTensor<int, cutlass::layout::TensorNCHW> test_nchw({1, 2, 2, 2});
			
int count = 0;
for (int i = 0; i < 2; i++) {
	for (int j = 0; j < 2; j++) {
		for (int k = 0; k < 2; k++) {
			test_nchw.at({ 0, i, j, k }) = example[count++];
		}
	}
}
for (int i = 0; i < 8; i++) {
	std::cout << test_nchw.host_data()[i] << std::endl;
}
std::cout << test_nchw.host_view() << std::endl;
```

The result is :
![image](https://user-images.githubusercontent.com/28353492/117987530-23e5c500-b36d-11eb-9af5-f233cca80687.png)

However, when we use `NHWC` instead, the result is:
![image](https://user-images.githubusercontent.com/28353492/117987696-50014600-b36d-11eb-8e4d-9f662d364cef.png)

This makes it difficult to use, especially when we want to use the `host_data` of `NCHW` to fill another `RowMajor` or `ColumnMajor` Matrix. Since it changes the layout in linear memory.

**Comment by hwu36** [comment]
> It seems this is not working for me. Just some compiling errors.

Sorry, I meant to put `temp_light_r.host_data()` and `layout` into a new `TensorRef` instead of the original `HostTensor`.  

Alternatively, you can also use `reset` method of `HostTensor` (https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/host_tensor.h#L179-L190), but it will reallocate device memory.

>  I noticed that the way how NCHW and NHWC organize data is different.

This is expected.  They are different in the offset calculation.  NHWC: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L116-L123.  NCHW:  https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L245-L251

**Comment by JasonChen9** [comment]
I encountered the same issue and am struggling to find a clear solution. Could you please provide a simple example to demonstrate how to change the tensor layout from cutlass::layout::RowMajor to cutlass::layout::TensorNHWC or similar? Any help would be appreciated!
