### ISSUE TITLE
limit in Epilogue capabilities?!

### ISSUE THREAD

**Issue by decioren** [NVIDIA/cutlass#276]
I am trying to write an epilogue that seems simple enough but ends up being very hard at the moment...
I need to carry out an operation similar to bias (hence starting from '17_fprop_per_channel_bias'). However, the bias uses the 'C' buffer and therefore has the type of the output. For quantized cases, where the output is int8 or lower, this makes no sense as the bias is supposed to be applied BEFORE the quantization. Hence the bias really should be of type 'ElementComputeEpilogue'.
In my specific case I need even more data for the 'bias' computation.
Trying o load the data inside the epilogue is hard because the information of which channel is used in which operation does not reach epilogue.

This seems to be a reasonable enough usage of CUTLASS. Is there a way to do this aesthetically?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-27

**Comment by hwu36** [comment]
Would you please show me the reference code like below?

```
(ElementAccum)accum(nhwc) = fprop();

/// Epilogue
for (int n = 0; n < N; ++n)
  for (int h = 0; h < H; ++h)
    for (int w = 0; w < W; ++w)
       for (int c = 0; c < C; ++c)
          (ElementOutput)output(nhwc) = (ElementOutput)(...(ElementAccum)accum(nhwc)...)
```

**Comment by decioren** [comment]
It would be something like:

for (int n = 0; n < N; ++n)
  for (int h = 0; h < H; ++h)
    for (int w = 0; w < W; ++w)
       for (int c = 0; c < C; ++c)
          (ElementOutput)output(nhwc) = (ElementOutput)( (ElementAccum)(accum(nhwc) * scale[c] + bias[c]))

the logic being that the accumulator is higher precision than the output. Hence scale and bias should be off type ElementAccum.
In my current case, the scale/bias are channel dependent, but I don't mind loading it as a fragment per nhwc using zero strides for nhw as the performance loss is negligible.

Does that answer your question?

**Comment by hwu36** [comment]
So, my understanding is that your `bias` is stored as `ElementAccum` instead of `ElementOutput` in the global memory.  So, you cannot use example `17_fprop_per_channel_bias` out of the box.

If my understanding is correct, you can just let tensor `C` and tensor `D` use different data types and pass them along the way, instantiate two output iterators based on the data types so that one can load `C` and one can store `D` (these two iterators need to process the same amount of data a time).  You need to do this change in at least these files:

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/device/implicit_gemm_convolution.h
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/default_conv2d_fprop.h
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/implicit_gemm_convolution.h
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h#L278-L363
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination.h

I understand debugging templates is tedious because `nvcc` error message is not very helpful.  Has to be patient :smile:

**Comment by decioren** [comment]
Thanks!
This will work indeed, but it is a very deep change and, as you say, tedious.
Is the following alternative possible?

Right now the elements inside the epilogue are anonymous, so I cannot tell the nhwc coordinate of each element. 
If I did know the coordinate per element (in my case just c) then I could load the extra data myself inside the epilogue (not using a fragment).
That way I would only need to write my own epilogue, which I need to do anyways and possibly
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/implicit_gemm_convolution.h #L321
so that the epilogue has the information that it needs to know the coordinate.
Even if the operation is not optimal in performance, it should still be negligible compared to the actual multiplication.

This is a much smaller change to the repo and is in line with the philosophy that the epilogue is responsible for the epilogue...
Possible?

**Comment by hwu36** [comment]
Honestly, I do not understand what you propose here.  However, if it works for you, that would be awesome!
