### ISSUE TITLE
[FEA] The procedural_name of TileDescription

### ISSUE THREAD

**Issue by qliu93** [NVIDIA/cutlass#286]
Hello, I'm reading the scripts in cutlass/tools/library and find it hard to understand why `TileDescription` gets its name in this format:

https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/library.py#L528

Why don't we use

``` python
"{}x{}x{}_{}x{}x{}_{}".format(tbm, tbn, tbk, warpm, warpn, warpk, statges)
```

Thanks

qliu93

**Comment by hwu36** [comment]
`tbk x stage` shows that how many elements in the k dimension are processed in one complete software pipeline.

We can add warp tile size to the kernel name so that we can tell if a kernel is using slice-k or not.  The downside is that the kernel name will be even longer.  Do you have interest in creating a PR?

**Comment by qliu93** [comment]
> We can add warp tile size to the kernel name so that we can tell if a kernel is using slice-k or not. The downside is that the kernel name will be even longer. Do you have interest in creating a PR?

Yes, I will try doing it today : )
