### ISSUE TITLE
performance in small blocks

### ISSUE THREAD

**Issue by wkjung** [NVIDIA/cutlass#31]
Hi,
From my experiment with _cutlass_perf_test_ on sgemm_nn, it seems that on small block size (e.g., 128,64,512) cutlass gets 3~10X slower in terms of flops.
How do I get a performance comparable to large block cases? Seems like changing only output tile shape doesn't work.

**Comment by kerrmudgeon** [comment]
Raw performance is unlikely to ever match peak performance of large-GEMM due to the lack of parallelism in small problems. However, with CUTLASS 1.2, we have added support for [parallelizing the reduction performed by GEMMs](https://github.com/NVIDIA/cutlass/blob/master/CUTLASS.md#parallel-reductions-across-gemm-k) which makes problems like these faster. 

I just ran the case I think you're suggesting with 20 partitions in the K dimension.

```$ ./tools/test/perf/cutlass_perf_test --m=128 --n=64 --k=512 --kernels=sgemm_128x64x8_splitk_pi_split20

============================================================================
Kernel: sgemm_128x32x8_splitk_pi_split32_nn
    problem: 128-by-64-by-512, A: column-major, B: column-major, beta: 0, batch: 1
    algorithm:   128x32_splitk_pi
    disposition: passed
    runtime:     0.0131456 ms

    performance: 638.13 GFLOPs
```

This is considerably faster than the basic 128x128x8 SGEMM kernel.
