### ISSUE TITLE
s8s8s32 Gemm with OpClassTensorOp cannot be compiled ,when the layout of A,B,C is RowMajor.

### ISSUE THREAD

**Issue by uiemUI** [NVIDIA/cutlass#311]
Code like the following will produce a compilation error
``` cpp

  using ElementOutput = int32_t;
  using ElementAccumulator = int32_t;
  using ElementCompute = int32_t;

  using Gemm = cutlass::gemm::device::Gemm<
      int8_t, cutlass::layout::RowMajor, int8_t, cutlass::layout::RowMajor,
      ElementOutput, cutlass::layout::RowMajor, ElementAccumulator,cutlass::arch::OpClassTensorOp,cutlass::arch::Sm75>;

  Gemm gemmop;

```

> In template: implicit instantiation of undefined template 'cutlass::gemm::warp::MmaTensorOpMultiplicandTileIterator<cutlass::PitchLinearShape<64, 64>, cutlass::gemm::Operand::kB, signed char, cutlass::layout::TensorOpMultiplicandCongruous<8, 128>, cutlass::PitchLinearShape<8, 16>, 1, 32, 1>'

Are there any ways to solve the error?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-15

**Comment by hwu36** [comment]
row x row is not supported.  The reason is that the tensor core instruction uses row x col layouts.  We have to transpose B operand if the input is row x row.   However `ldmatrix` can only transpose 16bit data, not 8bit.  Thus we cannot support it and we have to require data to be contiguous in the gemm-k dimension.

If you have to use row x row, you can choose to use the simt version which uses `idp4a` instruction.
