### ISSUE TITLE
usage of threadfence in conv

### ISSUE THREAD

**Issue by mengchihe** [NVIDIA/cutlass#359]
Hi, I have some question about the threadfence in implicit_gemm_convolution.h
With my understanding, the data write by the previous block will flush to L2 when release the semaphore which use st.global.release.gpu, thus when next block can get the semaphore, the data is already in L2, so why should there be a __threadfence() after semaphore.wait(), thanks.

**Comment by kerrmudgeon** [comment]
To be completely honest, I do not believe that __threadfence() is necessary nor in the right place, upon reflection. :)

The intent with the semaphores is to achieve a deterministically ordered serial reduction among CTAs using acquire-release semantics as described in ​the [PTX memory consistency](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#release-acquire-patterns) documentation.

```
Some sequences of instructions give rise to patterns that participate in memory synchronization 
as described later. The release pattern makes prior operations from the current thread visible to 
some operations from other threads. The acquire pattern makes some operations from other threads 
visible to later operations from the current thread.
```

The call to `Semaphore::wait()` issues PTX's `ld.global.acquire.gpu` which establishes visibility of previous stores by the releasing CTA to the CTA which acquired the semaphore. 

When the current thread issues `Semaphore::release()`, this issues PTX's `st.global.release.gpu` which ensures prior stores from the releasing CTA are visible to other threads which eventually acquire the semaphore. 

It doesn't seem like we need an actual `__threadfence()` to achieve this since the acquire-release semantics should be sufficient. If I remove the `__threadfence()` call entirely, the resulting disassembly seems to reasonably order the memory instructions and passes some random test cases on hardware.

```c++
  // cutlass/conv/kernel/implicit_gemm_convolution.h - no-threadfence

  // Acquire the semaphore - ensure Global Memory stores from the previous CTA are visible w.r.t the semaphore acquire
  semaphore.wait(threadblock_tile_idx.k());
  #if 0
        /*4760*/                   LDG.E.STRONG.GPU R138, [UR14] ; 
        /*4770*/                   CCTL.IVALL ;
  #endif
  
  // Run efficient epilogue - load [weakly] from Global Memory and store [weakly] to Global Memory
  epilogue(output_op, iterator_D, accumulators, iterator_C);
  
  // Release the semaphore - ensure previous Global Memory stores from this CTA are ordered w.r.t. the semaphore release
  semaphore.release(lock);
  #if 0
        /*8d50*/                   MEMBAR.ALL.GPU ;
        /*8d60*/                   IADD3 R0, R201, 0x1, RZ ;
        /*8d70*/                   ISETP.NE.AND P0, PT, R0, c[0x0][0x1b0], PT ;
        /*8d80*/                   SEL R0, R0, RZ, P0 ;
        /*8d90*/                   ERRBAR;
        /*8da0*/                   STG.E.STRONG.GPU [UR14], R0 ;
  #endif
```

I think we will remove the unnecessary `__threadfence()` call from Implicit GEMM and GEMM in a future release.

Thanks for raising this question.

**Comment by manishucsd** [comment]
Sharing some visual related to discussion here. Specifically, the visual below showcase the following statement by @kerrmudgeon  "The intent with the semaphores is to achieve a deterministically ordered serial reduction"

![Screen Shot 2021-11-09 at 9 10 47 AM](https://user-images.githubusercontent.com/3487276/140976269-5c35ee11-4830-4818-bddf-fe279a247618.png)

**Comment by mengchihe** [comment]
Thank you very much for the detailed explain
