### ISSUE TITLE
strange compilation error "error: ThreadMultiplyAdd is not a template"

### ISSUE THREAD

**Issue by edimetia3d** [NVIDIA/cutlass#44]
In the current master branch of  commit 877bdcace6d765359833101f6eabd5036d607a33

When compiling `Igemm`, it seems that the marco  `#if (!defined(__CUDA_ARCH__) || (__CUDA_ARCH__ >= 610))`  has some kind of impact on compilation

For example, if you delete the `#if (!defined(__CUDA_ARCH__) || (__CUDA_ARCH__ >= 610))` and `#endif`
in `cutlass/tools/test/unit/gemm/igemm_128x128x32.cu`, then compile the unit test,  compiler will report an error
```shell
cutlass/cutlass/gemm/igemm_traits.h(69): error: ThreadMultiplyAdd is not a template
````

I have test it in two of my platform , and the error occurs in both. 

Could someone give me some advice how this happens ?

**Comment by NikitaMishin** [comment]
If I understand correctly, it seems that macro used specifically for DP4A ( https://devblogs.nvidia.com/mixed-precision-programming-cuda-8/ ), so, basically this is mean that your platform doesn't support specified compute capability or you compile for not appropriate architecture or with the wrong sm_xx. 
About error. Also not quite understand this type of error (specifically, it's meaning) --- in my mind, this refers to undefined trait due to code inside define didn't process. 
Hope that someone more experienced with cutlass could provide a detailed answer with more explanation

**Comment by kerrmudgeon** [comment]
This seems like a good explanation.

I suggest using CUDA 10.2 Toolkit, and best performance is possible on NVIDIA Volta and Turing GPU archiectures. 

Note also that we have substantially refactored CUTLASS with the version 2.0 release in November 2019. You may have a good experience for mixed-precision integer GEMM kernels with the current codebase, particularly if you intend to target Turing's integer-valued Tensor Core operations.

Feel free to reopen if you continue to have trouble.

Thanks!
