### ISSUE TITLE
[QST] Confuse about the layout transpose checking in GemmUniversalAdapter.

### ISSUE THREAD

**Issue by JamesTheZ** [NVIDIA/cutlass#611]
I am confused about the transpose checking of the following code:
https://github.com/NVIDIA/cutlass/blob/ca23ff7924c3ed6c9a7457db3b20d351f468d3da/include/cutlass/gemm/device/gemm_universal_adapter.h#L57-L58

While I notice the checking is different with that of the following code:
https://github.com/NVIDIA/cutlass/blob/ca23ff7924c3ed6c9a7457db3b20d351f468d3da/include/cutlass/gemm/kernel/default_gemm_grouped.h#L186

When I try to use the following code to compute for a batched-GEMM, the result is not correct.
```cpp
using LayoutInputA = cutlass::layout::ColumnMajor;
using LayoutInputB = cutlass::layout::ColumnMajor;
using LayoutOutput = cutlass::layout::RowMajor;

using GemmKernel = cutlass::gemm::device::GemmUniversal<
    ElementInputA, LayoutInputA, ElementInputB, LayoutInputB, ElementOutput,
    LayoutOutput, ElementAccumulator, MMAOp, SmArch, ShapeMMAThreadBlock,
    ShapeMMAWarp, ShapeMMAOp, EpilogueOp, SwizzleThreadBlock, NumStages>::GemmKernel;

using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;

int const lda = length_m;
int const ldb = length_k;
int const ldd = length_n; // row major

long long int batch_stride_A =
    static_cast<long long int>(lda) * static_cast<long long int>(length_k);
long long int batch_stride_B = static_cast<long long int>(length_k);
long long int batch_stride_D =
   static_cast<long long int>(ldd) * static_cast<long long int>(length_m); // row major

typename Gemm::Arguments arguments{
  cutlass::gemm::GemmUniversalMode::kBatched,  // GemmUniversalMode
  problem_size,  // problem size of matrix multiplication
  batch_count,   // batch_count

  {alpha, beta},  // EpilogueOutputOp::Params

  tensor_a.device_data(),  // pointer to matrix A on device
  tensor_b.device_data(),  // pointer to matrix B on device
  nullptr,                 // no bias
  tensor_d.device_data(),  // pointer to matrix D on device

  batch_stride_A,
  batch_stride_B,
  0,
  batch_stride_D,

  lda,
  ldb,
  0,
  ldd};
```
When I change the RowMajor of the checking to ColumnMajor of the following code, the result becomes correct.
https://github.com/NVIDIA/cutlass/blob/ca23ff7924c3ed6c9a7457db3b20d351f468d3da/include/cutlass/gemm/device/gemm_universal_adapter.h#L57-L58

Is it a bug or I am not using the API correctly?

**Comment by hwu36** [comment]
Yeah, there is some confusion here, but not a bug.

Since you use `cutlass::gemm::device::GemmUniversal`, you don't need to use `cutlass::gemm::device::GemmUniversalAdapter`.  Just set `using Gemm = cutlass::gemm::device::GemmUniversal<ElementInputA, LayoutInputA, ...>`

You can take a look at https://github.com/NVIDIA/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu

**Comment by JamesTheZ** [comment]
I know that `GemmUniversal` is enough. What I need to do is to extend existing code to support some complex epilogues. I create a new class by defining `GemmKernel` as following:
```cpp
  using GemmKernel = kernel::GemmUniversal<
    typename DefaultGemmKernel::Mma,
    Epilogue, // customized epilogue structure.
    ThreadblockSwizzle
  >;
```
I just want to use `GemmUniversalAdapter ` as the uniformed interface to call my GEMM implementation and find the result is not correct. After replacing my GEMM with the standard `GemmUniversal `, the result is still not correct.

Is there some way to tackle this problem? Or it is just not legal to feed `kernel::GemmUniversal` to `GemmUniversalAdapter` and I have to create a new class to call?

**Comment by hwu36** [comment]
CUTLASS only implements row major epilogue because the tensor core output is row major.  To support column major output, we need to do this transform: A x B = C:col => B' x A' = C:row.

`GemmUniversal` has a partial specialization for Column Major C and it can do the above transformation internally.

`GemmUniversalAdaptor` is written for the CUTLASS profiler.  CUTLASS profiler tries to mimic cuBLAS which only has column major output.  It expects the user to do the above transformation manually when instantiating `GemmKernel`.

So it is easier to just use `GemmUniversal` as your uniform interface instead of using `GemmUniversalAdaptor`.

Since you wrote your own epilogue, you know your layout requirement best.  You certainly can write your own device level interface which is just plumbing.

**Comment by JamesTheZ** [comment]
I see. Thanks for the detailed explanation!
