### ISSUE TITLE
[QST] How should I set batch_stride of gemm_universal?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#702]
According to https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L619-L621
```c++
else if (params.mode == GemmUniversalMode::kGemmSplitKParallel) {
   ptr_D += threadblock_tile_offset.k() * params.batch_stride_D;
 }
```
 If I want to use split-k mode, I guess the batch_stride_D should be something like batch_count*ldd. Is it correct?

**Comment by jackkosaian** [comment]
Hi, @umiswing.

You'll want `batch_stride_D` to be `problem.m() * problem.n()`. You can see this from an example of using split-K, and setting `batch_stride_D` to this value [here](https://github.com/NVIDIA/cutlass/blob/master/examples/23_ampere_gemm_operand_reduction_fusion/ampere_gemm_operand_reduction_fusion.cu#L442).

Here's how to think about why this is the case:

Split K can be thought of decomposing a GEMM of size `M x N x K` into a batch of `split_k_slices` GEMMs of size `M x N x (K / split_k_slices)`. The output of each slice in the GEMM is written to a separate space in memory, so the overall output size is `split_k_slices * M * N`. Thus, the slice with index `k` (i.e., `threadblock_tile_offset.k()`) should write to the `k`th chunk of size `M * N` in the output. The calculation you link above advances the `D` pointer to this position. That is why we want `batch_stride_D` to be `problem_size.m() * problem_size.n()`.

Once all results are written, split K requires a reduction step to aggregate the partial results from each slice.

I hope this helps!

**Comment by umiswing** [comment]
@jackkosaian Thanks! I read the code in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_with_k_reduction.h, https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_splitk_parallel.h and https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h and still have some questions:
1. ```gemm_universal``` and ```gemm_splitk_parallel``` kernel provides a split-k parallel mode but doesn't have a reduce kernel. According to my understanding, it's in the split-k serial mode without the reduce kernel. Why it's still named split-k parallel mode?
2. In ```gemm_with_k_reduction``` kernel, the ```params.ptr_D``` points to a separate space according to https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_with_k_reduction.h#L271. However, it seems that ```params.ptr_D``` doesn't point to a separate space in the implementation of ```gemm_universal``` and ```gemm_splitk_parallel``` kernel. Why does cutlass still advance ```params.ptr_D``` with ```stride=MXN``` in ```gemm_universal``` and ```gemm_splitk_parallel``` kernel? 
3. What is the difference between [gemm_universal](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h), [gemm_splitk_parallel](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_splitk_parallel.h) and [gemm_with_k_reduction](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_with_k_reduction.h#L271) in the context of split-k parallel mode? Do they do the same thing in split-k parallel mode?
I'm adding split-k parallel mode to grouped-gemm in my case, so I want to learn more about it. Will be very grateful for your help!

**Comment by jackkosaian** [comment]
Hi, @umiswing.

> 1. gemm_universal and gemm_splitk_parallel kernel provides a split-k parallel mode but doesn't have a reduce kernel. According to my understanding, it's in the split-k serial mode without the reduce kernel. Why it's still named split-k parallel mode?

`GemmSplitKParallel` does provide a reduction kernel (see [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_splitk_parallel.h#L378)). It is named split K "parallel" mode because, unlike serial split K, it does not serialize before performing the epilogue, which is required for serial split K (see [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm.h#L339-L371)).

> 2. In gemm_with_k_reduction kernel, the params.ptr_D points to a separate space according to https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_with_k_reduction.h#L271. However, it seems that params.ptr_D doesn't point to a separate space in the implementation of gemm_universal and gemm_splitk_parallel kernel. Why does cutlass still advance params.ptr_D with stride=MXN in gemm_universal and gemm_splitk_parallel kernel?

Note that, for `GemmSplitKParallel` does set pointer D to a different, larger allocation: the pointer is set [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_splitk_parallel.h#L289-L314) and its size determined [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_splitk_parallel.h#L270). Thus, it makes sense that `ptr_D` is advanced by `MxN` in this case.

Note also that, if using `GemmUniversal` with mode `GemmUniversalMode::kGemmSplitKParallel`, it is expected that one provide a larger workspace and set `ptr_D` to this value. You can see this being done by the CUTLASS profiler (which uses `GemmUniversalAdapter`, which is similar to `GemmUniversal`): [here](https://github.com/NVIDIA/cutlass/blob/master/tools/profiler/src/gemm_operation_profiler.cu#L1107-L1113), we override ptr_D, and [here ](https://github.com/NVIDIA/cutlass/blob/master/tools/profiler/src/gemm_operation_profiler.cu#L1126-L1136) we call a reduction kernel. Thus, it also makes sense to advance `ptr_D` by `MxN` in `GemmUniversal`.

> 3. What is the difference between [gemm_universal](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h), [gemm_splitk_parallel](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_splitk_parallel.h) and [gemm_with_k_reduction](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_with_k_reduction.h#L271) in the context of split-k parallel mode? Do they do the same thing in split-k parallel mode?

For the `kernel::`-scoped implementations that you list:
* `kernel::GemmUniversal` with mode `GemmUniversalMode::kGemmSplitKParallel` will be equivalent to `kernel::GemmSplitKParallel`. The difference comes to fore for the `device::`-scoped kernels, wherein `device::GemmSplitKParallel` calls a reduction kernel and `device::GemmUniversal` does not. However, it is recommended that you use `device::GemmUniversal` rather than `device::GemmSplitKParallel`, as the former is more-frequently tested.
* As for `GemmWithKReduction`: as described [here](https://github.com/NVIDIA/cutlass/blob/master/examples/23_ampere_gemm_operand_reduction_fusion/ampere_gemm_operand_reduction_fusion.cu#L32-L41), this kernel enables one to perform a reduction along the K dimension for one of the A/B operands while the GEMM is being computed. The portions related to split K in `GemmWithKReduction` have been copied from `GemmUniversal`.

> I'm adding split-k parallel mode to grouped-gemm in my case

Adding split-K-like functionality for grouped GEMM interesting, but you may want to consider a few things:
1. It may be preferable to use stream-k (which was described in the [Fall 2022 CUTLASS GTC talk](https://www.nvidia.com/en-us/on-demand/session/gtcfall22-a41131/)). Stream K has some similarities to split K, but provides additional benefits.
2. Both grouped GEMM and split K have the goal of saturating the GPU with many small problems. Thus, it may be the case that running the two of them together will provide little benefit. If possible, consider trying a simple benchmark where you take your grouped GEMM workload, but split it into a `split_k_slices` more of GEMMs that each have a smaller value of K (`K / split_k_slices`). This will tell you the potential benefit you'd potentially gain from splitting the K dimensions of the GEMMs in your group, though it would not model any performance penalty that will be incurred due to needing to reduce the splits.

I hope this helps!

**Comment by umiswing** [comment]
@jackkosaian Thank you for the detailed answer. I am so grateful! I understand how it works now! :)
