### ISSUE TITLE
[QST] Does PyCUTLASS support sm!=80?

### ISSUE THREAD

**Issue by shintaro-iwasaki** [NVIDIA/cutlass#708]
As far as I tried PyCUTLASS on V100, it caused several issues.

One of the errors happened here where, seemingly, it should exclude all `-arch=sm_*` for host-side compilation while it handles only `-arch=sm_80`. https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/pycutlass/src/pycutlass/compiler.py#L311

Does PyCUTLASS only support `sm_80`? If so, can it show an error somewhere? Maybe I just missed something, but it'd be appreciated if [README.md](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/pycutlass/README.md) could explain it.

**Comment by jackkosaian** [comment]
Hi, @shintaro-iwasaki.

Thank you for bringing this to our attention. You can indeed use the CUTLASS Python interface with compute capabilities other than SM80, though you're correct that the line in you bring up above currently limits this possibility. We will refactor this and the examples to support other architectures.

In the meantime, you can enable other architectures by changing the [line ](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/pycutlass/src/pycutlass/compiler.py#L311 )you link above from:
```python
if opt not in ['-default-device', '-std=c++11', '-arch=sm_80', '-Xcicc', '-Xllc']:
```

to

```python
if opt not in ['-default-device', '-std=c++11', '-Xcicc', '-Xllc'] and '-arch=sm_' not in opt:
```

To run the basic GEMM example on V100 (similarly, for the basic Conv2d and grouped GEMM examples), you'll also need to change the [instruction shape](https://github.com/NVIDIA/cutlass/blob/master/examples/40_cutlass_py/gemm.py#L82) used to be `[8, 8, 4]`.

**Comment by shintaro-iwasaki** [comment]
It works with your suggestions. Thanks @jackkosaian!

> We will refactor this and the examples to support other architectures.

Yes that'd be great!

---

The question has already been answered, so please close this issue if we shouldn't use this place to track this PyCUTLASS sm!=80 support issue.

**Comment by jackkosaian** [comment]
Hi, @Llcoolsouder.

Volta Tensor Core operations only support operations of shape `[8, 8, 4]` and F16 data types. Thus, attempting to use either other data types with this instruction shape or other instruction shapes with this data type (and `OpClassTensorOp`) will not work.

This requirement is enforced by what is available in the Volta hardware, rather than by CUTLASS itself. To see which Tensor Core operation shapes and types are available on different architectures, you can browse [this section](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-mma) of the PTX documentation (specifically, the portion in that section with the heading "PTX ISA Notes")
