### ISSUE TITLE
[QST] how to determine legal configs for conv2d_fprop_s1688 instance?

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#724]
**What is your question?**
I adapted from the CUTLASS conv2d example and customized my application code snippet as follows:
```
using ElementAccumulator = float;
using ElementComputeEpilogue = float;
using ElementInputA = float;
using ElementInputB = float;
using ElementOutput = float;

using LayoutInputA = cutlass::layout::TensorNHWC;
using LayoutInputB = cutlass::layout::TensorNHWC;
using LayoutOutput = cutlass::layout::TensorNHWC;

using ThreadblockShape = cutlass::gemm::GemmShape<128, 128, 32>;
using WarpShape = cutlass::gemm::GemmShape<32, 64, 16>;
using InstructionShape = cutlass::gemm::GemmShape<16, 8, 8>;

constexpr int NumStages = 5;

using EpilogueOp = cutlass::epilogue::thread::LinearCombination<
    ElementOutput,
    2,
    ElementAccumulator,
    ElementComputeEpilogue>;

using Conv2dFpropKernel = typename cutlass::conv::kernel::DefaultConv2dFprop<
  ElementInputA, LayoutInputA,
  ElementInputB, LayoutInputB,
  ElementOutput, LayoutOutput,
  ElementAccumulator,
  cutlass::arch::OpClassTensorOp,
  cutlass::arch::Sm80,
  ThreadblockShape,
  WarpShape,
  InstructionShape,
  EpilogueOp,
  cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>,
  NumStages,
  cutlass::arch::OpMultiplyAddFastF32,
  cutlass::conv::IteratorAlgorithm::kOptimized,
  cutlass::conv::StrideSupport::kStrided,
  2,
  2
>::Kernel;
```

With the above configuration, I managed to compile my application with nvcc, but it gives runtime error:

> exec error: [/xxx/cutlass_tensorop_s1688_f32_fprop_optimized_64x128x32_16x64x16_stage5_nhwc_align1.cu] Got cutlass error: Error Internal at: 110

My problem size is _1,326,326,4,7,7,64,2,0,1_ (formatted as <N, H, W, C, R, S, K, stride, pad, dilation>).
Therefore, I'm wondering if given input problem size, how to pre-check if codes using my specified config parameters (such as tile shape, num_stage, align, etc) can be **both compiled and executed successfully**?

**Comment by jackkosaian** [comment]
Hi, @TUMSchieben.

## Relating to the specific case you bring up
For your specific case, it appears that your kernel configuration results in each block using too many registers. When I compile the kernel you've described, `cuobjdump --dump-resource-usage $object_file` says that the kernel will use 248 registers.

The launch configuration for your kernel will use 512 threads per block. This is determined by performing an element-wise division of `ThreadblockShape` by `WarpShape`, taking the product of the resultant vector to get the number of warps per threadblock, and multiplying the result by 32 (i.e., the number of threads per warp). For your case, this is `32 * (128  / 32) * (128 / 64) * (32 / 16) = 32 * 4 * 2 * 2 = 512`.

This results in a requirement of 248 registers/thread * 512 threads/block = 126976 registers/block, which exceeds the maximum number of 32-bit registers per SM on SM80 of [64K](https://docs.nvidia.com/cuda/ampere-tuning-guide/index.html#sm).

To fix this, you can reduce one of the dimensions of ThreadblockShape you use by a factor of 2. For example, changing to `<128, 128, 16>` will result in only 256 threads/block, and thus a total of 246 * 256 = 62976 registers/block, which is within the 64K limit (note that the number of registers/thread changed from 248 to 246 with this change in ThreadblockShape -- this is due to the compiler's allocation of registers).

## Avoiding compilation and runtime errors more generally
Avoiding all compilation and runtime errors ahead of time is difficult. Here are some guidelines to help you avoid common causes of these errors.

### Reducing compilation errors
Most compilation errors result from specifying a combination of template parameters that is unsupported. This often results in an error of the form "incomplete type is not allowed." Unfortunately, this error does not typically help in determining which template parameters are incorrect.

To reduce the likelihood of compilation errors, I suggest looking through the configurations of operations generated in [generator.py](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py). This script is called via CUTLASS's CMake system to generate operations that can be used by the CUTLASS profiler. It enumerates combinations of threadblock/warp/instruction shapes and the datatypes/alignments supported by them. It is not exhaustive, but gives a good starting point for configurations that will compile on a given architecture.

### Reducing runtime errors
Most runtime errors are a result of either (1) launching a kernel that uses too many resources for the device on which you run, or (2) launching a kernel with an input that does not match the requirements of the kernel you specified.

#### Checking that kernel launches don't require too many resources
Each device has a maximum set of resources that can be used (e.g., shared memory and registers per SM, threads that can be launched, etc.). When these are exceeded, your kernel will compile, but will fail at launch time with a CUDA error of "too many resources requested for launch."

We'll next walk through how to detect whether the CUTLASS kernel you've compiled will exceed the resources available on the device you will run on.

##### Too many registers
As described previously, each SM has 64K registers. Thus, each threadblock can use no more than 64K registers. To determine whether our kernel configuration will exceed this value, we need to know the number of threads per block in our kernel and the number of registers used per thread.

CUTLASS determines the number of warps per block based on the number of `WarpShape` tiles that fit in a `ThreadblockShape` tile. The total number of threads is thus: `threads_per_block = 32 * (threadblock.m / warp.m) * (threadblock.n / warp.n) * (threadblock.k / warp.k)` .

To figure out the number of registers that will be used per thread, you can run `cuobjdump --dump-resource-usage $object_file` on the object file of the compiled kernel. You should see a column of the form `REG:248`, which indicates that each thread uses 248 registers.

You can multiply the number of threads per block by the number of registers per thread to determine the registers used per block. If this exceeds 64K, you will need to change your kernel configuration, likely by reducing the `ThreadblockShape`.

##### Too much shared memory
Each SM has a limited amount of shared memory. If a kernel requires more shared memory than available on the SM, the kernel launch will fail. To determine whether this will take place, we need to know the amount of shared memory that will be used per threadblock and the amount of shared memory available per SM.

CUTLASS kernels keep threadblock-tile-sized operands in shared memory. Specifically, the amount of shared memory required for a given kernel will be `num_stages * (sizeof(ElementA) * (threadblock.m * threadblock.k) + sizeof(ElementB) * (threadblock.k * threadblock.n))`.

The amount of shared memory available per SM of a given device can be determined by using the [cudaGetDeviceProperties ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g1bf9d625a931d657e08db2b4391170f0) API and using the `sharedMemPerBlockOptin` property returned (this is the amount of available shared memory per SM).

Typically, if your CUTLASS kernel uses more shared memory than available per SM, you will either want to reduce the number of stages used or the `ThreadblockShape`.

#### Catching misaligned inputs
If you do not have resource-related issues described above, your kernel may be failing due to having a misaligned input. You can check that the problem size you use matches the alignment requirements of the kernel in question by checking the portions of the kernel that check for misaligned inputs (e.g., [here](https://github.com/NVIDIA/cutlass/blob/c975e2ccbb2dbf13024568b37ffa3498ed0b3aed/include/cutlass/gemm/kernel/gemm_universal.h#L377-L402)).

---

I hope this helps! Please keep in mind that these suggestions will not eliminate compilation/runtime errors. They are simply an enumeration of common culprits.

**Comment by mnicely** [comment]
Hi @TUMSchieben are you able to provide any information on your application?

**Comment by TUMSchieben** [comment]
> Hi, @TUMSchieben.
> 
> ## Relating to the specific case you bring up
> For your specific case, it appears that your kernel configuration results in each block using too many registers. When I compile the kernel you've described, `cuobjdump --dump-resource-usage $object_file` says that the kernel will use 248 registers.
> 
> The launch configuration for your kernel will use 512 threads per block. This is determined by performing an element-wise division of `ThreadblockShape` by `WarpShape`, taking the product of the resultant vector to get the number of warps per threadblock, and multiplying the result by 32 (i.e., the number of threads per warp). For your case, this is `32 * (128 / 32) * (128 / 64) * (32 / 16) = 32 * 4 * 2 * 2 = 512`.
> 
> This results in a requirement of 248 registers/thread * 512 threads/block = 126976 registers/block, which exceeds the maximum number of 32-bit registers per SM on SM80 of [64K](https://docs.nvidia.com/cuda/ampere-tuning-guide/index.html#sm).
> 
> To fix this, you can reduce one of the dimensions of ThreadblockShape you use by a factor of 2. For example, changing to `<128, 128, 16>` will result in only 256 threads/block, and thus a total of 246 * 256 = 62976 registers/block, which is within the 64K limit (note that the number of registers/thread changed from 248 to 246 with this change in ThreadblockShape -- this is due to the compiler's allocation of registers).
> 
> ## Avoiding compilation and runtime errors more generally
> Avoiding all compilation and runtime errors ahead of time is difficult. Here are some guidelines to help you avoid common causes of these errors.
> 
> ### Reducing compilation errors
> Most compilation errors result from specifying a combination of template parameters that is unsupported. This often results in an error of the form "incomplete type is not allowed." Unfortunately, this error does not typically help in determining which template parameters are incorrect.
> 
> To reduce the likelihood of compilation errors, I suggest looking through the configurations of operations generated in [generator.py](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py). This script is called via CUTLASS's CMake system to generate operations that can be used by the CUTLASS profiler. It enumerates combinations of threadblock/warp/instruction shapes and the datatypes/alignments supported by them. It is not exhaustive, but gives a good starting point for configurations that will compile on a given architecture.
> 
> ### Reducing runtime errors
> Most runtime errors are a result of either (1) launching a kernel that uses too many resources for the device on which you run, or (2) launching a kernel with an input that does not match the requirements of the kernel you specified.
> 
> #### Checking that kernel launches don't require too many resources
> Each device has a maximum set of resources that can be used (e.g., shared memory and registers per SM, threads that can be launched, etc.). When these are exceeded, your kernel will compile, but will fail at launch time with a CUDA error of "too many resources requested for launch."
> 
> We'll next walk through how to detect whether the CUTLASS kernel you've compiled will exceed the resources available on the device you will run on.
> 
> ##### Too many registers
> As described previously, each SM has 64K registers. Thus, each threadblock can use no more than 64K registers. To determine whether our kernel configuration will exceed this value, we need to know the number of threads per block in our kernel and the number of registers used per thread.
> 
> CUTLASS determines the number of warps per block based on the number of `WarpShape` tiles that fit in a `ThreadblockShape` tile. The total number of threads is thus: `threads_per_block = 32 * (threadblock.m / warp.m) * (threadblock.n / warp.n) * (threadblock.k / warp.k)` .
> 
> To figure out the number of registers that will be used per thread, you can run `cuobjdump --dump-resource-usage $object_file` on the object file of the compiled kernel. You should see a column of the form `REG:248`, which indicates that each thread uses 248 registers.
> 
> You can multiply the number of threads per block by the number of registers per thread to determine the registers used per block. If this exceeds 64K, you will need to change your kernel configuration, likely by reducing the `ThreadblockShape`.
> 
> ##### Too much shared memory
> Each SM has a limited amount of shared memory. If a kernel requires more shared memory than available on the SM, the kernel launch will fail. To determine whether this will take place, we need to know the amount of shared memory that will be used per threadblock and the amount of shared memory available per SM.
> 
> CUTLASS kernels keep threadblock-tile-sized operands in shared memory. Specifically, the amount of shared memory required for a given kernel will be `num_stages * (sizeof(ElementA) * (threadblock.m * threadblock.k) + sizeof(ElementB) * (threadblock.k * threadblock.n))`.
> 
> The amount of shared memory available per SM of a given device can be determined by using the [cudaGetDeviceProperties ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g1bf9d625a931d657e08db2b4391170f0) API and using the `sharedMemPerBlockOptin` property returned (this is the amount of available shared memory per SM).
> 
> Typically, if your CUTLASS kernel uses more shared memory than available per SM, you will either want to reduce the number of stages used or the `ThreadblockShape`.
> 
> #### Catching misaligned inputs
> If you do not have resource-related issues described above, your kernel may be failing due to having a misaligned input. You can check that the problem size you use matches the alignment requirements of the kernel in question by checking the portions of the kernel that check for misaligned inputs (e.g., [here](https://github.com/NVIDIA/cutlass/blob/c975e2ccbb2dbf13024568b37ffa3498ed0b3aed/include/cutlass/gemm/kernel/gemm_universal.h#L377-L402)).
> 
> I hope this helps! Please keep in mind that these suggestions will not eliminate compilation/runtime errors. They are simply an enumeration of common culprits.

Thx for the reply. It's rather comprehensive!
