### ISSUE TITLE
[QST]Doubts about the use of cutlass profiler

### ISSUE THREAD

**Issue by suguanger** [NVIDIA/cutlass#738]
Hi! When I used the cutlass profiler tool, I found that the instruction shapes,warp shapes and thread-block shapes was set by some specified value in tools/library/scripts/generator.py, may I know why it is set like these? Can I set other values? If these parameters are considered as adjustable， can I tune from a bigger search space to find a better performance? Or if we want to set these values ourselves, what suggestions and guidance do we have?

**Comment by hwu36** [comment]
Instruction shape is decided by the HW.  If we have infinite resource, we would like to have biggest square tile size because it has best math/mem ratio.  However, warp shape is bounded by register numbers.  Usually we use 32x32 or 64x64 depends on the problem size.  Threadblock shape is bounded by the shared memory capacity, occupancy, thread number, etc.  We usually use 4 or 8 warps.

Profiler includes the most plausible tile sizes and they should be good for the majority cases.  Some legal tile sizes are not included, but they may only be useful for unusual problem sizes.  CUTLASS 2.11 has stream-k now which can allow you try even less tile sizes to get the best perf.

**Comment by suguanger** [comment]
> Instruction shape is decided by the HW. If we have infinite resource, we would like to have biggest square tile size because it has best math/mem ratio. However, warp shape is bounded by register numbers. Usually we use 32x32 or 64x64 depends on the problem size. Threadblock shape is bounded by the shared memory capacity, occupancy, thread number, etc. We usually use 4 or 8 warps.
> 
> Profiler includes the most plausible tile sizes and they should be good for the majority cases. Some legal tile sizes are not included, but they may only be useful for unusual problem sizes. CUTLASS 2.11 has stream-k now which can allow you try even less tile sizes to get the best perf.


Thank you for your patience and detailed answer. If we want to use the stream-k you mentioned above, it is a new feature, how can we learn its' usage,? Do you provide a corresponding DEMO? Where can I find that? Thank you very much!

**Comment by hwu36** [comment]
we will post an example soon.

**Comment by mnicely** [comment]
Posted example for stream-k
