### ISSUE TITLE
[BUG] Compile Error: no suitable conversion function from "const half" to "float" exists

### ISSUE THREAD

**Issue by ZhangZhiPku** [NVIDIA/cutlass#746]
**Describe the bug**
I try to use MSVC 14.0 and Cuda 11.3 to compile Cutlass with Windows 11, however it shows following error:

    h:/python/projects/cutlass_ppq/ppq/csrc/cutlass/include\cutlass/float8.h(400): error: no suitable conversion function from "const half" to "float" exists
    
    h:/python/projects/cutlass_ppq/ppq/csrc/cutlass/include\cutlass/float8.h(414): error: no instance of constructor "__half::__half" matches the argument list
                argument types are: (float)
    
    h:/python/projects/cutlass_ppq/ppq/csrc/cutlass/include\cutlass/float8.h(610): error: no suitable conversion function from "const half" to "float" exists
    
    h:/python/projects/cutlass_ppq/ppq/csrc/cutlass/include\cutlass/float8.h(624): error: no instance of constructor "__half::__half" matches the argument list
                argument types are: (float)

It seems there is a missing conversion function here(from float to cutlass::half).
I don't konw why it happens in windows, and i think it will be fine with linux.

**Steps/Code to reproduce bug**
I was using Ninja to compile cutlass project, and error happened there.

**Expected behavior**
Fix this problem by adding a conversion function here.

**Environment details (please complete the following information):**
Windows 11
MSVC 14.0
Cuda 11.3

**Comment by hwu36** [comment]
@jackkosaian it is about fp8

**Comment by jackkosaian** [comment]
Hi, @ZhangZhiPku.

Apologies for the late reply on this.

Are you by chance running into this error when building a PyTorch CUDA extension? I see `python` in the paths you mention, and you mention using ninja, which PyTorch extensions are often built with.

I ask because this error may arise from PyTorch extensions adding the following flags to compilation:
```
-D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__
```
See [this post](https://discuss.pytorch.org/t/cuda-no-half2-operators-for-cuda-9-2/18365/4) for a description of why this takes place.

The `__CUDA_NO_HALF_CONVERSIONS__` flag seems to disable implicit conversions between `half` and other types. For example, rather than being able to perform `float(half_variable)`, one would need to use the explicit `__half2float(half_variable)`. Based on my experience, I expect this will occur on either Linux or Windows.

To see whether these changes would fix your issue, could you please try applying the following patch to float8.h (in the latest version of CUTLASS as of this writing -- commit hash [ce8597dc14b2e84e0661093ed255c888606ef672](https://github.com/NVIDIA/cutlass/tree/ce8597dc14b2e84e0661093ed255c888606ef672))?

```diff
diff --git a/include/cutlass/float8.h b/include/cutlass/float8.h
index 93e3209c..de32a218 100644
--- a/include/cutlass/float8.h
+++ b/include/cutlass/float8.h
@@ -399,7 +399,7 @@ struct alignas(1) float_e4m3_t : float8_base<FloatEncoding::E4M3> {

         return *reinterpret_cast<float_e4m3_t *>(&tmp);
     #else
-        return bitcast(Base::convert_float_to_fp8(float(flt)));
+        return bitcast(Base::convert_float_to_fp8(__half2float(flt)));
     #endif
     }

@@ -413,7 +413,7 @@ struct alignas(1) float_e4m3_t : float8_base<FloatEncoding::E4M3> {

         return reinterpret_cast<half2 const &>(packed).x;
     #else
-        return half(Base::convert_fp8_to_float(x.storage));
+        return __float2half(Base::convert_fp8_to_float(x.storage));
     #endif
     }

@@ -425,7 +425,7 @@ struct alignas(1) float_e4m3_t : float8_base<FloatEncoding::E4M3> {
         uint32_t packed;
         asm volatile("cvt.rn.f16x2.e4m3x2 %0, %1;\n" : "=r"(packed) : "h"(bits));

-        return float(reinterpret_cast<half2 const &>(packed).x);
+        return __half2float(reinterpret_cast<half2 const &>(packed).x);
     #else
         return Base::convert_fp8_to_float(x.storage);
     #endif
@@ -609,7 +609,7 @@ struct alignas(1) float_e5m2_t : float8_base<FloatEncoding::E5M2> {

         return *reinterpret_cast<float_e5m2_t *>(&tmp);
     #else
-        return bitcast(Base::convert_float_to_fp8(float(flt)));
+        return bitcast(Base::convert_float_to_fp8(__half2float(flt)));
     #endif
     }

@@ -623,7 +623,7 @@ struct alignas(1) float_e5m2_t : float8_base<FloatEncoding::E5M2> {

         return reinterpret_cast<half2 const &>(packed).x;
     #else
-        return half(Base::convert_fp8_to_float(x.storage));
+        return __float2half(Base::convert_fp8_to_float(x.storage));
     #endif
     }

@@ -635,7 +635,7 @@ struct alignas(1) float_e5m2_t : float8_base<FloatEncoding::E5M2> {
         uint32_t packed;
         asm volatile("cvt.rn.f16x2.e5m2x2 %0, %1;\n" : "=r"(packed) : "h"(bits));

-        return float(reinterpret_cast<half2 const &>(packed).x);
+        return __half2float(reinterpret_cast<half2 const &>(packed).x);
     #else
         return Base::convert_fp8_to_float(x.storage);
     #endif
```

**Comment by jackkosaian** [comment]
The changes described above have been added in https://github.com/NVIDIA/cutlass/pull/857.
