### ISSUE TITLE
[QST] conv2d_fprop algorithm for proper problem size

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#750]
**What is your question?**
Hi there,
I noticed that for ampere_tensorop_conv2dfprop, different iterator algorithms can be used and I also found the following code:
```
enum class IteratorAlgorithm { 
  kAnalytic,      ///< functionally correct in all cases but lower performance
  kOptimized,     ///< optimized for R <= 32, S <= 32 and unity-stride dgrad
  kFixedChannels, ///< Analytic algorithm optimized for fixed channel count (C == AccessSize)
  kFewChannels,   ///< Analytic algorithm optimized for few channels (C divisible by AccessSize)
  kFixedStrideDilation ///< Optimized for fixed stride and dilation
};
```
My question is:
1. Given a problem size <N,H,W,C,R,S,K,stride,pad,dilation>, what is the exact constraint to use any of the iterator algorithms above? Eg. when I use `IteratorAlgorithm::kOptimized` for C=3, the program would give runtime error.
2. Given a problem size <N,H,W,C,R,S,K,stride,pad,dilation>, how can I choose the proper algorithm in order to get the optimal performace?

Thanks in advance!

**Comment by hwu36** [comment]
Usually just use `kOptimized` for the best perf.  `kAnalytic` is created for us to debug `kOptimized`.  `kFixedStrideDilation` is used by strided dgrad, not fprop.  `kFixedChannels` and `kFewChannels` are used when `C` is tiny which is usually the case for the first several layers.

The failure of your `C = 3` is caused by alignment issues.  You need to change the alignment to 1.  However, alignment = 1 performance won't be great.   If possible, you can pad it to 4 or 8 to run together with `kFixedChannels` to get the best perf.

**Comment by TUMSchieben** [comment]
> Usually just use `kOptimized` for the best perf. `kAnalytic` is created for us to debug `kOptimized`. `kFixedStrideDilation` is used by strided dgrad, not fprop. `kFixedChannels` and `kFewChannels` are used when `C` is tiny which is usually the case for the first several layers.
> 
> The failure of your `C = 3` is caused by alignment issues. You need to change the alignment to 1. However, alignment = 1 performance won't be great. If possible, you can pad it to 4 or 8 to run together with `kFixedChannels` to get the best perf.

Since `kOptimized` is used for `R <= 32, S <= 32` case, what is the best-fit algorithm for `R >32 or S > 32` case?

**Comment by hwu36** [comment]
You can use `kAnalytic`

**Comment by mnicely** [comment]
@TUMSchieben has your question been answered?
