### ISSUE TITLE
[DOC]

### ISSUE THREAD

**Issue by jiangzzsss** [NVIDIA/cutlass#769]
## Report needed documentation

**Report needed documentation**
Hi, we'd like to implement a fused kernel using PyTorch's extension where GEMM is included. Since cutlass is currently the most powerful code for writing cuda based codes and due to its widely usage, we hope to embed cutlass code into our fused kernel.
I'm kind of new to c++ template, so I find it is troublesome to do the fusing.

Our kernel structure looks like this:
```
template <typename scalar_t> 
__global__ void fused_kernel(
.........
){  
 // 1. ThreadBlock cutlass code for GEMM , we need the results in shared memory
 // 2. our own function, does bilinear sampling, we perform input data reading from previous GEMM results in shared memory
}
```
we need to use Threadblock level cutlass codes because our second step need results from several threads,
and to utilize cutlass's optimization as much as possible.
**we hope to have a doc to tutor how to use Threadblock level cutlass inside a kernel.**

**Describe the documentation you'd like**
1. Threadblock-level GEMM example code that is inside a PyTorch extension kernel or can be correctly called. 
2. Doc that gives a guide to fuse kernels: one is using the API of cutlass, and one being totally user's own code(naive cuda c++ codes)

**Steps taken to search for needed documentation**
1. searching cutlass's official documentation;
2. browsing cutlass's source code and notes to determine.

**Comment by Jack47** [comment]
@hwu36  hi haicheng，great thanks for your links. epilogue is very useful to do element-wise fuse. We want to fuse bilinear into gemm, bilinear will visit four elements in two adjacent rows:
![image](https://user-images.githubusercontent.com/1720972/212131011-b6131eec-f74c-46d9-abf2-10b85d79c467.png)

questions:
1. does epilogue has examples to show visit two rows?
2. any experience on the hurt of the fusion benefits? no kernel fusions vs all visit global memory in kernel fusion

currently we want to find ways to ensure we can use cutlass to do bilinear sampling fusion and the upper and lower benefit boundaries. any input appreciated~

**Comment by hwu36** [comment]
if it requires communication across different threadblocks, we usually punt because it is hard to write the code and the return is small or negative.

We compute the row number in the overall matrix here: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h#L419 .  You can backtrack from this line to find how thread, warp, threadblock offset is computed. 

data is loaded from the shared memory from this line https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue.h#L347.  you can add some row delta to fetch data from different rows.

**Comment by mnicely** [comment]
@jiangzzsss we have new Python Interface coming soon to improve the ability to integrate CUTLASS into PyTorch. 
@jackkosaian for vis
