### ISSUE TITLE
[QST] fMHA example o_strideM

### ISSUE THREAD

**Issue by tianleiwu** [NVIDIA/cutlass#771]
**What is your question?**
I saw o_strideM of the fMHA example is patched in a few applications like:

https://github.com/AITemplate/cutlass/commit/f434be22a6270f9f000712286f92545ccca045b7

https://github.com/Oneflow-Inc/oneflow/blob/e79298104b56b00f23394523505d09469bb89063/oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu#L109

and in the original code from xFormers:
https://github.com/facebookresearch/xformers/blob/1191f035e8aa06241850dedf2c20d66f5b3ba575/xformers/csrc/attention/cuda/fmha/kernel_forward.h#L127

Could you check whether the change of o_strideM shall be applied?

**Comment by hwu36** [comment]
@terrychenism and @danthe3rd 

I think ait changed it to save a permutation. Ait and xformers developers can explain it better than I do.  If they think I should make the change, I am happy to do it.

**Comment by danthe3rd** [comment]
Hi,

In CUTLASS, I used the shape `[B, H, M, K]` for the attention inputs, to match the [previous multi_head_attention](https://github.com/NVIDIA/cutlass/tree/v2.10.0/examples/41_multi_head_attention) example.
In xFormers, the attention inputs have shape [B, M, H, K]. This is commonly the case in practice, because it's coming from the output of a linear layer as a `[B, M, H * K]` tensor, so it's more intuitive and might avoid data copies, as the output will likely have to be reshaped to `[B, M, H*K]`.

In both cases, we want the output to match the input shape. Because the output is contiguous, we can deduce the strides for dimension M from the shape, so it's either "K" for the shape `[B, H, M, K]` in CUTLASS, or "K * H" for the shape `[B, M, H, K]` in xformers/AITemplate.

**Comment by tianleiwu** [comment]
@danthe3rd, thanks for the effort. We prefer [B, M, H, K] as well since it could avoid extra transpose for inputs/outputs.
