### ISSUE TITLE
[QST] Got cutlass error: Error Internal at: 500

### ISSUE THREAD

**Issue by ShqWW** [NVIDIA/cutlass#778]
**Describe the bug**
When i run the depthwise convolution example
`./46_depthwise_simt_conv2dfprop`
, it report a bug:
`Got cutlass error: Error Internal at: 500`

My GPU is Titan Xp, the cuda version is 11.8, and I compile the cutlass with -DCUTLASS_NVCC_ARCHS=80;

**Comment by jackkosaian** [comment]
Hi, @ShengqiWang.

I think there are two issues here.

>My GPU is Titan Xp, the cuda version is 11.8, and I compile the cutlass with -DCUTLASS_NVCC_ARCHS=80;

Note that Titan Xp has compute capability of 6.1. Thus, you should use ` -DCUTLASS_NVCC_ARCHS=61`

Even after making this change, I also saw an error when attempting to reproduce the issue on P100 (which is similar to Titan Xp, but has compute capability 6.0). By adding the following code [here](https://github.com/NVIDIA/cutlass/blob/8b42e751c63ba219755c8ed91af5f6ec1ecc1ee6/include/cutlass/conv/device/direct_convolution.h#L230), one can determine that the error is being caused by the fact that the default configuration in example 46 uses more shared memory than is available on the P100:

```c++
    if (status != cudaSuccess) {
      std::cout << "CUDA ERROR: " << cudaGetErrorString(status) << std::endl;
      std::cout << "Smem size is: " << smem_size << std::endl;
      cudaDeviceProp properties;
      int device_idx;
      cudaError_t result = cudaGetDevice(&device_idx);
      result = cudaGetDeviceProperties(&properties, device_idx);
      std::cout << "Available smem is: " << properties.sharedMemPerBlockOptin << std::endl;
      return Status::kErrorInternal;
    }
```

This printed out:
```
CUDA ERROR: invalid argument
Smem size is: 59392
Available smem is: 49152
Got cutlass error: Error Internal at: 500
```

To reduce the amount of shared memory used by the kernel, you can reduce the `NumStages` parameter [here](https://github.com/NVIDIA/cutlass/blob/8b42e751c63ba219755c8ed91af5f6ec1ecc1ee6/examples/46_depthwise_simt_conv2dfprop/depthwise_simt_conv2dfprop.cu#L127). Changing this parameter to `2` caused the example to work for me.

I hope this helps!

**Comment by ShengqiWang** [comment]
In reality， I have tried -DCUTLASS_NVCC_ARCHS=60， 61 and 80. But when I compile with 61 and 61， there is another issue. 
When i run
`cmake .. -DCUTLASS_NVCC_ARCHS="60;61" -DCUTLASS_LIBRARY_OPERATIONS=conv2d` 

and
`./tools/profiler/cutlass_profiler --operation=conv2d --n=8 --h=224 --w=224 --c=128 --k=128 --r=3 --s=3`
there is no output. And there is a normal output with 80.

**Comment by mnicely** [comment]
@ShqWW has your issue been resolved?

**Comment by Gaffey** [comment]
@jackkosaian I had the same problem. I followed this issue by setting filtershape to 5, 5 and changing numstages to 2 to avoid insufficient smem. It works well. But when I enlarge the kernel size to 7, even `numstages 2` is not sufficient for me (with Nvidia V100). Setting numstages to 1 leads to incorrect and random results so I think the least number of numstages is 1. How can I solve the insufficient smem problem? I want to test the performance of larger kernels such as 17 or 13.

**Comment by jackkosaian** [comment]
Hi, @Gaffey. I am unable to reproduce this. When I run the example with a `7x7` filter using 2 stages, I see ~61 KB of shared memory being used, whereas the V100 has 96 KB of shared memory.

Could you please paste the diff of your changes to example 46 that is causing you to hit this error?

**Comment by Gaffey** [comment]
> Hi, @Gaffey. I am unable to reproduce this. When I run the example with a `7x7` filter using 2 stages, I see ~61 KB of shared memory being used, whereas the V100 has 96 KB of shared memory.
> 
> Could you please paste the diff of your changes to example 46 that is causing you to hit this error?

I changed the data format from float32 to float16, and then I make it to run the example with a `7x7` filter. However, it is impossible to run a `17x17` filter. I try to modify the var `groups_per_cta` to 32 and find that the performance is harmed. Is there any better methods?

**Comment by jackkosaian** [comment]
Thank you for clarifying.

> I try to modify the var groups_per_cta to 32

You're on the right track by reducing parameters like this. To reduce the shared memory used, one must reduce either the activation size or filter size (see how shared memory used is calculated from these parameters [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/direct_convolution.h#L158)). Since you are fixing filter size, your best bet will be to try to reduce activation size. You can see the parameters that go into this component [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/depthwise_direct_conv_params.h#L126-L137).

> and find that the performance is harmed

What is the baseline you are comparing against when you state that performance is "harmed?" You are right that it is typically preferable to use larger thread block shapes. However, in this case, reducing thread block shape is necessary for the kernel to run at all.

**Comment by Ethan-Yan27** [comment]
A general way to reduce the smem usage is to reduce the threadBlockOutputShape size , filterShape size, or group_per_cta.
If none of these settings work, then try the [kAnalytic](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/depthwise_conv2d_fprop_implicit_gemm_f16nhwc_f16nhwc_f16nhwc_simt_f16_sm60.cu) version which uses conv2d algorithm.

> However, it is impossible to run a 17x17 filter. I try to modify the var groups_per_cta to 32 and find that the performance is harmed.

Group_per_cta could be 16 as well. With below settings,  the smem usage is around 46KB for float16, 
```
// This code section describes the groups a thread block will compute
constexpr int groups_per_cta = 16;

// This code section describes the output tile <N, O, P, Q> a thread block will compute
using ThreadBlockOutputShape = cutlass::conv::TensorNHWCShape<1, 8, 8, groups_per_cta>;

// This code section describes the filter shape <R, S>
using FilterShape = cutlass::MatrixShape<17, 17>;

// Number of pipelines you want to use
constexpr int NumStages = 2;
```

If without splitK, the perf of Group_per_cta =16 is better than Group_per_cta =32 on my local ampere GPU.
```
# Group_per_cta =16
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,128,128,32,32,17,17,32,1,1,1,1,1,14.7565,20.5359

# Group_per_cta =32
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,128,128,32,32,17,17,32,1,1,1,1,1,17.0999,17.7216
```

To improve the perf, splitK option is a big hammer. Here is the result on my local ampere GPU.
With Group_per_cta =16,  if I enable the splitK, the perf would be much better than w/o splitK. `--splitk=108`
```
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,128,128,32,32,17,17,32,1,1,1,1,108,0.45568,665.025
```
