### ISSUE TITLE
[QST] Does generator.py cover most of the possible configuration?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#809]
I find [generator.py](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py) doesn't cover all possible layout (e.g. all row-major, which is a possible combination in cutlass). I guess it's because generator.py is written for generating kernel later used by profiler. But except the layout, does generator.py cover most of the possible configuration? I'm writing scripts to generate all possible kernels in my case and want to confirm this.

**Comment by jackkosaian** [comment]
Hi, @umiswing.  `generator.py` does cover most, but not all possible configurations of kernels. It does typically contain configurations that are expected to achieve high performance on large problem sizes (e.g., configurations with large threadblock tile shapes).

Some examples of configurations that are not currently covered in `generator.py` include:
* All possible stage counts that will work with a particular configuration (e.g., only some are chosen [here](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/generator.py#L1867-L1888))
* All possible threadblock cluster shapes that will work with a particular configuration (e.g., only some are chosen [here](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/generator.py#L4035-L4046), whereas more may be supported in [unit tests](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/test/unit/gemm/device/sm90_gemm_f16_f16_f16_tensor_op_f32_cluster_warpspecialized.cu#L71))
* Currently, CUTLASS 3.0 GEMMs generated by `generator.py` [leverage](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/gemm_operation.py#L628-L629) the `CollectiveBuilder` interface (see the documentation [here ](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/media/docs/gemm_api_3x.md#collective-builder-for-collectivemmas) and [example 49](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/examples/49_hopper_gemm_schedules_with_collective_builder/49_hopper_gemm_schedules_with_collective_builder.cu#L32-L99) for more details on this). This interface selects some kernel configurations on behalf of the user, thus, naturally limiting the number of configurations that can be expressed through the interface (albeit, to those that are expected to be most performant). In particular, CUTLASS 3.0 GEMMs generated by `generator.py` currently [leverage](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/gemm_operation.py#L628-L629) the `StageCountAuto` and `KernelScheduleAuto` parameters of the `CollectiveBuilder`, which allows the `CollectiveBuilder` to select a stage count and kernel schedule automatically, rather than using one passed in by the user. Thus, not all stage counts or kernel schedules will currently be generated (e.g., for the `CollectiveBuilder` currently in CUTLASS 3.0, [persistent warp-specialized kernels](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/media/docs/efficient_gemm.md#warp-specialization) will not be generated through `generator.py`).

Finally, `generator.py` does not generate kernels for some of the fused epilogues available in CUTLASS.

**Comment by hwu36** [comment]
generator.py only has col major output to match cublas.  You could do A x B = C:row -> B' x A' = C:col to find the corresponding row major kernel.

**Comment by umiswing** [comment]
Thanks. 
```generator.py``` is helpful. I write some scripts based on it to generate the kernel I need.
