### ISSUE TITLE
[QST] Why we set the grid shape to be (tile_shape.n(), tiled_shape.m(), tiled_shape.k()) when launching the SplitK kernel?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#821]
In `gemm_split_parallel.h`, we first partition the problem into tiles using:

``` 
GemmCoord get_tiled_shape( 
    GemmCoord problem_size,
    GemmCoord tile_size,
    int partitions) const {

    return GemmCoord(
      (problem_size.m() + tile_size.m() - 1) / tile_size.m(),
      (problem_size.n() + tile_size.n() - 1) / tile_size.n(),
      partitions);
  }  
```

It meansing that we partition the result matrix's shape into tiles of `(problem_size.m() + tile_size.m() - 1) / tile_size.m()` rows and `(problem_size.n() + tile_size.n() - 1) / tile_size.n()` columns, and each tile's accumulation is splited into `partitions`  slices.
However, we set the grid shape to be `(tile_shape.n(), tiled_shape.m(), tiled_shape.k())` in `GemmSplitKHorizontalThreadblockSwizzle` when launching the kernel. Correspondingly, we get the blockIdx by `(blockIdx.Y, blockIdx.X. blockIdx.Z)`. 
I have tested the performance between this imdirect method and direct method `(tiled_shape.m(), tiled_shape.n(), tiled_shape.k())` to launch the kernel which shows that they nearly have the same FLOPS. 
So I am wondering why CUTLASS use this imdirect method to launch the kernel: ). 
Sincerely thank you for your help!

**Comment by hwu36** [comment]
All the swizzling functors in this file are used to improve the memory efficiencies.  No one actually works better than any other  one in all the cases.

As to your question, we do this because it is `Horizontal` as suggested in the struct name.

In fact, we use [gemm_universal](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal.h) to process regular gemm, splitk gemm, batch gemm.  We usually use [GemmIdentityThreadblockSwizzle](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/threadblock_swizzle.h#L57) as the swizzling functor for gemm_universal.

**Comment by Ther-LF** [comment]
Get it! Thank you~ :-)
