### ISSUE TITLE
[QST] Does the more numStages I set, the better performance I get?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#854]
Hello! I'm working for auto tuning for examples/36. I write some scripts to generate all the kernels configuration based on https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py. According to https://github.com/NVIDIA/cutlass/issues/617, some configurations will require more shared memory than available. So I need to remove some configurations. https://github.com/NVIDIA/cutlass/issues/617 says I can calculate the amount of shared memory needed for a GEMM as follows: ```((threadblockM * threadblockK * sizeof(ElementA)) + (threadblockN * threadblockK * sizeof(ElementB))) * numStages```. I think it may be a good idea to decrease the numStages so I can still keep some of the tiling size. Does the more numStages I set, the better performance it will be (so that I can set only one numStages for each tile size and avoid a long tuning time)? If not, do you have some empirical range for numStages?

**Comment by hwu36** [comment]
> Does the more numStages I set, the better performance it will be

No.  On ampere, the minimum stage is 3.  The bigger the tile size is, the smaller the stage number need to be.  Big stage will also hurt the occupancy because of the increased shared memory usage.  If the stage is bigger than needed, the start of the mma operation will be pushed back.  If the stage is smaller than needed, the start of the mma has to wait for the data.

You can start from the stage number used by the profiler, and search a better one for your case around that number.

**Comment by umiswing** [comment]
Thanks.

**Comment by irasin** [comment]
hi, @hwu36, I was wondering why the minimum stage is 3 on ampere?

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/mma_multistage.h#L489

because of this line.  it is stage is 2, 2-2=0 which means we need to wait for all cp.async finishes, then no data movement and math overlap.
