### ISSUE TITLE
[QST] How to quickly convert an int8_t HostTensor to an int4b_t HostTensor on the device?

### ISSUE THREAD

**Issue by Barrot** [NVIDIA/cutlass#866]
**What is your question?**
I have a mixed precision model that has an `int8_t` input but needs to feed an `int4b_t` tensor to the next convolution layer.
Conversion from `int8_t` to `cutlass::int4b_t` is not straight forward.
1. `NumericalConversions` is not able to accomplish this.
2. `ImplicitGemm` does not take `int8_t` tensors A and B with an `int4b_t` tensor C.
3. Copy device to device supports only the same precisions for the source and the destination.
4. Writing a custom kernel is not as straight forward because indexing into `HostTensor<int4b_t,...>.device_data()` is misleading. Doing something like:
```cuda
template<typename A, typename B>
__global__ void Convert(A *tensorDataA, B *tensorDataB, uint32_t N)
{
    int idx_x = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx_x < N) tensorDataB[idx_x] = static_cast<B>(tensorDataA[idx_x]);
}
.
.
.
int numBlocks = (outputSize.product() + 1024) / 1024;
std::cout << "Num Blocks: " << numBlocks << std::endl;

ConvertInt8toInt4<int8_t, cutlass::int4b_t><<<numBlocks, 1024>>>(outputTensor.device_data(),
                                                                     tensorInt4.device_data(),
                                                                     tensorInt4.extent().product());
```
will result an out of bound access in the `tensorInt4`.

Is there a way to efficiently convert `int8_t` tensors to `int4b_t` tensors on the device or is it a requirement to copy the data from the device to the host, to convert, and then to sync it back to the device?

**Comment by hwu36** [comment]
Sorry for the late response.  There is no ptx that can do any int->s4 conversion for you.  So that you need to write something yourself and don't expect it to be fast.

First, you need to use https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/subbyte_reference.h#L606 to index into `int4b_t` array.  example: https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/warp/testbed.h#L82

You may also need to add an ctor that uses int8 here: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/integer_subbyte.h  or you may want to write a new `NumericConverter` in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/numeric_conversion.h
