### ISSUE TITLE
[QST] How to use “split_k_slices” and splitK mode in conv2d_frop?

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#867]
**What is your question?**
Hi all,

I noticed that in https://github.com/NVIDIA/cutlass/blob/master/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu#L283, we can set `split_k` in conv2d fprop. So when will we use this setting? Also for split_k we can use `serial` or `parallel` split mode, then in which cases will these settings be used?

Thanks!

**Comment by jackkosaian** [comment]
I'm not sure that I follow your question. Are you referring to [example 16](https://github.com/NVIDIA/cutlass/blob/master/examples/16_ampere_tensorop_conv2dfprop/ampere_tensorop_conv2dfprop.cu#L490-L502) instead, which contains a convolution, rather than example 14?

>So when will we use this setting? 

Could you describe in a little bit more detail what your confusion is? Thanks.

>Also for split_k we can use serial or parallel split mode, then in which cases will these settings be used?

Could you see whether the discussion in https://github.com/NVIDIA/cutlass/issues/702 helps?

In addition to https://github.com/NVIDIA/cutlass/issues/702, here are some differences between the `SplitKMode::kSerial` and `SplitKMode::kParallel` variants:

`SplitKMode::kSerial`
* Performs GEMM + split-K reduction in a single kernel
* Requires synchronization to serialize the reduction across threadblocks
* Does not require additional workspace

`SplitKMode::kParallel`
* Performs GEMM and split-K reduction in separate kernels
* Does not require synchronization between threadblocks in the GEMM
* Does require additional workspace

**Comment by TUMSchieben** [comment]
> I'm not sure that I follow your question. Are you referring to [example 16](https://github.com/NVIDIA/cutlass/blob/master/examples/16_ampere_tensorop_conv2dfprop/ampere_tensorop_conv2dfprop.cu#L490-L502) instead, which contains a convolution, rather than example 14?
> 
> > So when will we use this setting?
> 
> Could you describe in a little bit more detail what your confusion is? Thanks.
> 
> > Also for split_k we can use serial or parallel split mode, then in which cases will these settings be used?
> 
> Could you see whether the discussion in #702 helps?
> 
> In addition to #702, here are some differences between the `SplitKMode::kSerial` and `SplitKMode::kParallel` variants:
> 
> `SplitKMode::kSerial`
> 
> * Performs GEMM + split-K reduction in a single kernel
> * Requires synchronization to serialize the reduction across threadblocks
> * Does not require additional workspace
> 
> `SplitKMode::kParallel`
> 
> * Performs GEMM and split-K reduction in separate kernels
> * Does not require synchronization between threadblocks in the GEMM
> * Does require additional workspace

Ah sorry, I do mean split_k in `conv2d_fprop`, not gemm. The code is here https://github.com/NVIDIA/cutlass/blob/master/examples/16_ampere_tensorop_conv2dfprop/ampere_tensorop_conv2dfprop.cu#L490
AFAIK, we can use split_k in gemm kernels, but is the setting exactly the same when used for conv2d_fprop kernels?
I notice that in example 30_wgrad_split_k, using `SplitKMode::kParallel` in conv2d_wgrad would need extra reduction kernel, so for conv2d_fprop case, is this extra reduction kernel also necessary? Thx

**Comment by jackkosaian** [comment]
Yes, you would need an extra reduction kernel when using Conv2d with `SplitKMode::kParallel`. For example, the CUTLASS profiler runs a reduction kernel [here ](https://github.com/NVIDIA/cutlass/blob/86cae03cea301817232290d231092ef2c18961d7/tools/profiler/src/conv2d_operation_profiler.cu#L816-L829) when profiling Conv2d kernels that leverage `SplitKMode::kParallel`.

**Comment by TUMSchieben** [comment]
Thanks for the explanation!
