### ISSUE TITLE
[QST] Is stream-k data-parallel hybridization needed when operands and output fit in L2?

### ISSUE THREAD

**Issue by rkindi** [NVIDIA/cutlass#901]
I was reading the [stream-k paper](https://arxiv.org/pdf/2301.03598.pdf) and trying to understand this section.

> The basic Stream-K decomposition can, in certain cases, exhibit tile-processing skew that leads to potentially adverse effects on cache performance. When the number of output tiles t is not an even multiple of the grid size g, the starting k-offset for the first MAC-loop iteration in each CTA will be different. Depending on the sizes and shapes of the input matrices and blocking factors, this skew may preclude these fragments from seeing reuse across CTAs in the GPU’s cache structure.

I was trying to understand in which cases the "potentially adverse effects on cache performance" can happen. One case I thought of was is when the operands and output do not fit into L2. So, something like this maybe:

* Some MAC loop iteration loads some (BLOCK_M, BLOCK_N, BLOCK_K) sized stuff, X, from global memory early on.
* But we have to evict X from L2 at some point along the way because our operands are very large.
* We need to load X again (or part of X) later on because of the stream-k but have an L2 miss. If we did data parallel hybridization instead, we could promote better L2 locality with by ordering the data parallel part more efficiently with [thread block rasterization](https://github.com/NVIDIA/cutlass/blob/master/media/docs/efficient_gemm.md#threadblock-rasterization) instead.

**But are there any cases where data-parallel hybridization needed when operands and output fit in L2? I don't think so because as long as the (BLOCK_M, BLOCK_N, BLOCK_K) sized operands you are trying to load into shared memory are present in L2, there is no issue, correct?**

<img width="833" alt="Screenshot 2023-04-01 at 9 34 20 PM" src="https://user-images.githubusercontent.com/9440135/229326382-c5db84b1-2e45-4cb8-94ef-61977e5947fe.png">

cc: @hwu36

**Comment by dumerrill** [comment]
In general, the matmul datasets (input operands and output) won't *entirely* fit in the cache hierarchy.  In the classic data-parallel formulation, however, concurrent threadblocks (CTAs) will be able to make temporal reuse of fragments in A and B because they happen to be working on the same k-iteration at the same time:

![image](https://user-images.githubusercontent.com/1476032/229573778-78f6320e-7ff6-4151-bdac-1f16609aaa78.png)

In the data-parallel illustration above, for example, the CTAs working on tiles 0 and 3 will be fetching the same fragment from the A matrix at some given time t[i].

However, this temporal coherence is unlikely to be the case for StreamK, as the tile-k-iteration for any two CTAs at any given point in time is unlikely to be the same:

![image](https://user-images.githubusercontent.com/1476032/229574448-8fb5ed24-4611-41c9-80ce-0485c4ff6eee.png)

In the streamk illustration above, the CTAs working on tiles 0 and 3 will be fetching different fragments from the A matrix at some given time t[i].  There will be no temporal reuse if the diversity of demand for A is great enough to trash the L2.
