### ISSUE TITLE
[BUG] constexpr function cannot have a nonliteral return type "dim3"

### ISSUE THREAD

**Issue by S-o-T** [NVIDIA/cutlass#923]
**Describe the bug**
Compilation fails with MSVC 19.35, nvcc 11.8, cutlass e36912f.
cutlass/gemm/kernel/sm70_gemm.hpp(147): error : a constexpr function cannot have
a nonliteral return type "dim3"
(same in a few other sources with "constexpr dim3")

**Steps/Code to reproduce bug**
Configure cutlass with default cmake options using msbuild generator and try to build. 

**Expected behavior**
Compilation succeed.

**Environment details (please complete the following information):**
MSVC 19.35, nvcc 11.8, cutlass e36912f

**Additional context**
Removing constexpr solves the problem.

**Comment by hwu36** [comment]
@d-k-b @mhoemmen

**Comment by mhoemmen** [comment]
@S-o-T Thanks for reporting!  This is likely due to a known MSVC issue, described in detail in this blog post: https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/ .

As described in the blog post, the fix is to set the `Zc:__cplusplus` compiler flag as well as `/std:c++17` (or later).  That should ensure that the `__cplusplus` macro has the correct value (`201703L` or larger).  Could you please try that and let us know if it works?  Thanks!

**Comment by S-o-T** [comment]
Thx for suggestion! Unfortunately setting suggested compiler flag and ensuring that __cplusplus macro evaluates to 201703L does not fix the problem.

**Comment by mhoemmen** [comment]
@S-o-T Thanks for reporting back!  We will look into a different approach for fixing this.

**Comment by mhoemmen** [comment]
@S-o-T Update: We would like to release this along with fixes for other MSVC build issues.  We're testing with MSVC right now.

**Comment by mhoemmen** [comment]
@S-o-T We plan to include these fixes in the next public release.  Thanks for reporting!

**Comment by S-o-T** [comment]
Good to know. Waiting to test it out.

**Comment by mnicely** [comment]
@S-o-T can you confirm v3.1 fixes your issues?

**Comment by S-o-T** [comment]
Yes, this problem is now fixed. Thank you!
