### ISSUE TITLE
Documentation for fused GEMM example

### ISSUE THREAD

**Issue by tgale96** [NVIDIA/cutlass#99]
Hello!

The new fused GEMM + GEMM example looks very interesting but I can't find any documentation explaining the scheme. Is there a plan to add details outside the code itself?

**Comment by jwang323** [comment]
Hi! We will add more comments and docs for this example. For now, please see the following as a brief description:

This example shows fusing 2 GEMMs into one kernel with performance measurement comparing with non-fused GEMMs. The 1st GEMM is relu(alpha\*A\*B) and 2nd GEMM is relu(alpha\*A\*B+beta\*C).

Problem size:

* GEMM1 (M,N,K): 128\*1600, 64, 576
* GEMM2 (M,N,K): 128\*1600, 128, 64

Note that GEMM1_N = GEMM2_K

The example requires # of thread blocks stay the same across 2 GEMMs and thread_block_tile_N = problem_N so the data required by each layer is thread-block-resident. It also requires warp_tile_N = thread_block_tile_N so the data required by each warp is register-file-resident.

Performance:

* fp16 on Tesla T4 @ 1590MHz (non-fused vs. fused): 1.39011 ms vs. 1.26035 ms
* int8 on Tesla T4 @ 1590MHz (non-fused vs. fused): 0.751759 ms vs. 0.62971 ms
* fp16 on Quadro RTX 8000 @ 1890MHz (non-fused vs. fused): 0.721144 ms vs. 0.629864 ms
* int8 on Quadro RTX 8000 @ 1890MHz (non-fused vs. fused): 0.379049 ms vs. 0.324764 ms

**Comment by tgale96** [comment]
Excellent! Thank you for the description.

**Comment by kerrmudgeon** [comment]
Thank you, @jwang323! I plan to update the documentation in the example with this information.

**Comment by Hecmay** [comment]
Hi, is there any update on the document? I was trying to read the source code of the fused GEMMs example. Some part of the source code still looks kind of confusing to me. Hope someone may help explain it a bit. 

1. What does B2bGemm mean? back to back? Is double buffer reused between the 2 GEMMs?
2. You mentioned that `thread_block_tile_N = problem_N = warp_tile_N`. It means that in the N's dimension, the # of tile is always 1? Is it possible to relax this constraint and support more flexible tile size?

**Comment by jwang323** [comment]
> 1. What does B2bGemm mean? back to back? Is double buffer reused between the 2 GEMMs?

[jw] Yes B2bGemm means back-to-back fused GEMMs. The output accumulator of the 1st GEMM will be stored in the register file and reused as the activation input of the 2nd GEMM. This saves a round trip to memory for the activation matrix.

> 2. You mentioned that `thread_block_tile_N = problem_N = warp_tile_N`. It means that in the N's dimension, the # of tile is always 1? Is it possible to relax this constraint and support more flexible tile size?

[jw] The example needs those constraints to work because it requires the output accumulator of the 1st GEMM to be register file-resident. To relax the constraints, the implementation methodology has to been changed:
- To relax thread_block_tile_N = warp_tile_N, each thread block will need to use shared memory to stage data so they are no longer register file-resident. 
- To relax problem_N = thread_block_tile_N, the output matrix of 1st GEMM is no longer block-resident so the thread blocks will have to exchange data through global memory for the 2nd GEMM.

**Comment by Hecmay** [comment]
Thank you for the explanation! @jwang323
